Insert Into Arl Values ('AXA COLPATRIA S.A.');
Insert Into Arl Values ('COLMENA SEGUROS');
Insert Into Arl Values ('COMPAÑÍA DE SEGUROS DE VIDA AURORA S.A.');
Insert Into Arl Values ('LA EQUIDAD SEGUROS DE VIDA');
Insert Into Arl Values ('LIBERTY SEGUROS DE VIDA S.A.');
Insert Into Arl Values ('MAPFRE SEGUROS');
Insert Into Arl Values ('POSITIVA');
Insert Into Arl Values ('SEGUROS BOLÍVAR S.A.');
Insert Into Arl Values ('SEGUROS DE VIDA ALFA S.A.');
Insert Into Arl Values ('SURATEP SA');
GO

Insert Into Department Values ('ANTIOQUIA', '05');
Insert Into Department Values ('ATLÁNTICO', '08');
Insert Into Department Values ('BOGOTÁ; D.C.', '11');
Insert Into Department Values ('BOLÍVAR', '13');
Insert Into Department Values ('BOYACÁ', '15');
Insert Into Department Values ('CALDAS', '17');
Insert Into Department Values ('CAQUETÁ', '18');
Insert Into Department Values ('CAUCA', '19');
Insert Into Department Values ('CESAR', '20');
Insert Into Department Values ('CÓRDOBA', '23');
Insert Into Department Values ('CUNDINAMARCA', '25');
Insert Into Department Values ('CHOCÓ', '27');
Insert Into Department Values ('HUILA', '41');
Insert Into Department Values ('LA GUAJIRA', '44');
Insert Into Department Values ('MAGDALENA', '47');
Insert Into Department Values ('META', '50');
Insert Into Department Values ('NARIÑO', '52');
Insert Into Department Values ('NORTE DE SANTANDER', '54');
Insert Into Department Values ('QUINDÍO', '63');
Insert Into Department Values ('RISARALDA', '66');
Insert Into Department Values ('SANTANDER', '68');
Insert Into Department Values ('SUCRE', '70');
Insert Into Department Values ('TOLIMA', '73');
Insert Into Department Values ('VALLE DEL CAUCA', '76');
Insert Into Department Values ('ARAUCA', '81');
Insert Into Department Values ('CASANARE', '85');
Insert Into Department Values ('PUTUMAYO', '86');
Insert Into Department Values ('ARCHIPIÉLAGO DE SAN ANDRÉS; PROVIDENCIA Y SANTA CATALINA', '88');
Insert Into Department Values ('AMAZONAS', '91');
Insert Into Department Values ('GUAINÍA', '94');
Insert Into Department Values ('GUAVIARE', '95');
Insert Into Department Values ('VAUPÉS', '97');
Insert Into Department Values ('VICHADA', '99');
GO

Insert Into Municipality Values ('Medellín', '5001', 1);
Insert Into Municipality Values ('Abejorral', '5002', 1);
Insert Into Municipality Values ('Abriaquí', '5004', 1);
Insert Into Municipality Values ('Alejandría', '5021', 1);
Insert Into Municipality Values ('Amagá', '5030', 1);
Insert Into Municipality Values ('Amalfi', '5031', 1);
Insert Into Municipality Values ('Andes', '5034', 1);
Insert Into Municipality Values ('Angelópolis', '5036', 1);
Insert Into Municipality Values ('Angostura', '5038', 1);
Insert Into Municipality Values ('Anorí', '5040', 1);
Insert Into Municipality Values ('Chimá', '68176', 21);
Insert Into Municipality Values ('Anza', '5044', 1);
Insert Into Municipality Values ('Apartadó', '5045', 1);
Insert Into Municipality Values ('Arboletes', '5051', 1);
Insert Into Municipality Values ('Argelia', '5055', 1);
Insert Into Municipality Values ('Armenia', '5059', 1);
Insert Into Municipality Values ('Barbosa', '5079', 1);
Insert Into Municipality Values ('Bello', '5088', 1);
Insert Into Municipality Values ('Betania', '5091', 1);
Insert Into Municipality Values ('Betulia', '5093', 1);
Insert Into Municipality Values ('Ciudad Bolívar', '5101', 1);
Insert Into Municipality Values ('Briceño', '5107', 1);
Insert Into Municipality Values ('Buriticá', '5113', 1);
Insert Into Municipality Values ('Cáceres', '5120', 1);
Insert Into Municipality Values ('Caicedo', '5125', 1);
Insert Into Municipality Values ('Caldas', '5129', 1);
Insert Into Municipality Values ('Campamento', '5134', 1);
Insert Into Municipality Values ('Cañasgordas', '5138', 1);
Insert Into Municipality Values ('Caracolí', '5142', 1);
Insert Into Municipality Values ('Caramanta', '5145', 1);
Insert Into Municipality Values ('Carepa', '5147', 1);
Insert Into Municipality Values ('Sampués', '70670', 22);
Insert Into Municipality Values ('Carolina', '5150', 1);
Insert Into Municipality Values ('Caucasia', '5154', 1);
Insert Into Municipality Values ('Chigorodó', '5172', 1);
Insert Into Municipality Values ('Cisneros', '5190', 1);
Insert Into Municipality Values ('Cocorná', '5197', 1);
Insert Into Municipality Values ('Concepción', '5206', 1);
Insert Into Municipality Values ('Concordia', '5209', 1);
Insert Into Municipality Values ('Copacabana', '5212', 1);
Insert Into Municipality Values ('Dabeiba', '5234', 1);
Insert Into Municipality Values ('Don Matías', '5237', 1);
Insert Into Municipality Values ('Ebéjico', '5240', 1);
Insert Into Municipality Values ('El Bagre', '5250', 1);
Insert Into Municipality Values ('Entrerrios', '5264', 1);
Insert Into Municipality Values ('Envigado', '5266', 1);
Insert Into Municipality Values ('Fredonia', '5282', 1);
Insert Into Municipality Values ('Giraldo', '5306', 1);
Insert Into Municipality Values ('Girardota', '5308', 1);
Insert Into Municipality Values ('Gómez Plata', '5310', 1);
Insert Into Municipality Values ('Nunchía', '85225', 26);
Insert Into Municipality Values ('Guadalupe', '5315', 1);
Insert Into Municipality Values ('Guarne', '5318', 1);
Insert Into Municipality Values ('Guatapé', '5321', 1);
Insert Into Municipality Values ('Heliconia', '5347', 1);
Insert Into Municipality Values ('Hispania', '5353', 1);
Insert Into Municipality Values ('Itagui', '5360', 1);
Insert Into Municipality Values ('Ituango', '5361', 1);
Insert Into Municipality Values ('Pamplona', '54518', 18);
Insert Into Municipality Values ('Jericó', '5368', 1);
Insert Into Municipality Values ('La Ceja', '5376', 1);
Insert Into Municipality Values ('La Estrella', '5380', 1);
Insert Into Municipality Values ('La Pintada', '5390', 1);
Insert Into Municipality Values ('La Unión', '5400', 1);
Insert Into Municipality Values ('Liborina', '5411', 1);
Insert Into Municipality Values ('Maceo', '5425', 1);
Insert Into Municipality Values ('Marinilla', '5440', 1);
Insert Into Municipality Values ('Montebello', '5467', 1);
Insert Into Municipality Values ('Murindó', '5475', 1);
Insert Into Municipality Values ('Mutatá', '5480', 1);
Insert Into Municipality Values ('Nariño', '5483', 1);
Insert Into Municipality Values ('Necoclí', '5490', 1);
Insert Into Municipality Values ('Nechí', '5495', 1);
Insert Into Municipality Values ('Olaya', '5501', 1);
Insert Into Municipality Values ('Peñol', '5541', 1);
Insert Into Municipality Values ('Peque', '5543', 1);
Insert Into Municipality Values ('Pueblorrico', '5576', 1);
Insert Into Municipality Values ('Puerto Berrío', '5579', 1);
Insert Into Municipality Values ('Puerto Nare', '5585', 1);
Insert Into Municipality Values ('Puerto Triunfo', '5591', 1);
Insert Into Municipality Values ('Remedios', '5604', 1);
Insert Into Municipality Values ('Retiro', '5607', 1);
Insert Into Municipality Values ('Rionegro', '5615', 1);
Insert Into Municipality Values ('Sabanalarga', '5628', 1);
Insert Into Municipality Values ('Sabaneta', '5631', 1);
Insert Into Municipality Values ('Salgar', '5642', 1);
Insert Into Municipality Values ('Albán', '25019', 11);
Insert Into Municipality Values ('Yavaraté', '97889', 32);
Insert Into Municipality Values ('San Francisco', '5652', 1);
Insert Into Municipality Values ('San Jerónimo', '5656', 1);
Insert Into Municipality Values ('Montelíbano', '23466', 10);
Insert Into Municipality Values ('Puerto Asís', '86568', 27);
Insert Into Municipality Values ('San Luis', '5660', 1);
Insert Into Municipality Values ('San Pedro', '5664', 1);
Insert Into Municipality Values ('Corozal', '70215', 22);
Insert Into Municipality Values ('San Rafael', '5667', 1);
Insert Into Municipality Values ('San Roque', '5670', 1);
Insert Into Municipality Values ('San Vicente', '5674', 1);
Insert Into Municipality Values ('Santa Bárbara', '5679', 1);
Insert Into Municipality Values ('Buesaco', '52110', 17);
Insert Into Municipality Values ('Santo Domingo', '5690', 1);
Insert Into Municipality Values ('El Santuario', '5697', 1);
Insert Into Municipality Values ('Segovia', '5736', 1);
Insert Into Municipality Values ('Sopetrán', '5761', 1);
Insert Into Municipality Values ('Támesis', '5789', 1);
Insert Into Municipality Values ('Tarazá', '5790', 1);
Insert Into Municipality Values ('Tarso', '5792', 1);
Insert Into Municipality Values ('Titiribí', '5809', 1);
Insert Into Municipality Values ('Toledo', '5819', 1);
Insert Into Municipality Values ('Turbo', '5837', 1);
Insert Into Municipality Values ('Uramita', '5842', 1);
Insert Into Municipality Values ('Urrao', '5847', 1);
Insert Into Municipality Values ('Valdivia', '5854', 1);
Insert Into Municipality Values ('Valparaíso', '5856', 1);
Insert Into Municipality Values ('Vegachí', '5858', 1);
Insert Into Municipality Values ('Venecia', '5861', 1);
Insert Into Municipality Values ('Maní', '85139', 26);
Insert Into Municipality Values ('Yalí', '5885', 1);
Insert Into Municipality Values ('Yarumal', '5887', 1);
Insert Into Municipality Values ('Yolombó', '5890', 1);
Insert Into Municipality Values ('Yondó', '5893', 1);
Insert Into Municipality Values ('Zaragoza', '5895', 1);
Insert Into Municipality Values ('Barranquilla', '8001', 2);
Insert Into Municipality Values ('Baranoa', '8078', 2);
Insert Into Municipality Values ('El Peñón', '13268', 4);
Insert Into Municipality Values ('Candelaria', '8141', 2);
Insert Into Municipality Values ('Galapa', '8296', 2);
Insert Into Municipality Values ('Tuluá', '76834', 24);
Insert Into Municipality Values ('Casabianca', '73152', 23);
Insert Into Municipality Values ('Luruaco', '8421', 2);
Insert Into Municipality Values ('Malambo', '8433', 2);
Insert Into Municipality Values ('Manatí', '8436', 2);
Insert Into Municipality Values ('Anolaima', '25040', 11);
Insert Into Municipality Values ('Piojó', '8549', 2);
Insert Into Municipality Values ('Polonuevo', '8558', 2);
Insert Into Municipality Values ('Chía', '25175', 11);
Insert Into Municipality Values ('San Andrés de Tumaco', '52835', 17);
Insert Into Municipality Values ('Sabanagrande', '8634', 2);
Insert Into Municipality Values ('Sabanalarga', '8638', 2);
Insert Into Municipality Values ('Santa Lucía', '8675', 2);
Insert Into Municipality Values ('Santo Tomás', '8685', 2);
Insert Into Municipality Values ('Soledad', '8758', 2);
Insert Into Municipality Values ('Suan', '8770', 2);
Insert Into Municipality Values ('Tubará', '8832', 2);
Insert Into Municipality Values ('Usiacurí', '8849', 2);
Insert Into Municipality Values ('Milán', '18460', 7);
Insert Into Municipality Values ('Capitanejo', '68147', 21);
Insert Into Municipality Values ('Achí', '13006', 4);
Insert Into Municipality Values ('Anzoátegui', '73043', 23);
Insert Into Municipality Values ('Arenal', '13042', 4);
Insert Into Municipality Values ('Arjona', '13052', 4);
Insert Into Municipality Values ('Arroyohondo', '13062', 4);
Insert Into Municipality Values ('Florida', '76275', 24);
Insert Into Municipality Values ('Calamar', '13140', 4);
Insert Into Municipality Values ('Cantagallo', '13160', 4);
Insert Into Municipality Values ('Cicuco', '13188', 4);
Insert Into Municipality Values ('Córdoba', '13212', 4);
Insert Into Municipality Values ('Clemencia', '13222', 4);
Insert Into Municipality Values ('Repelón', '8606', 2);
Insert Into Municipality Values ('El Guamo', '13248', 4);
Insert Into Municipality Values ('Frontino', '5284', 1);
Insert Into Municipality Values ('Magangué', '13430', 4);
Insert Into Municipality Values ('Mahates', '13433', 4);
Insert Into Municipality Values ('Margarita', '13440', 4);
Insert Into Municipality Values ('Montecristo', '13458', 4);
Insert Into Municipality Values ('Mompós', '13468', 4);
Insert Into Municipality Values ('Morales', '13473', 4);
Insert Into Municipality Values ('Norosí', '13490', 4);
Insert Into Municipality Values ('Pinillos', '13549', 4);
Insert Into Municipality Values ('Regidor', '13580', 4);
Insert Into Municipality Values ('Río Viejo', '13600', 4);
Insert Into Municipality Values ('San Estanislao', '13647', 4);
Insert Into Municipality Values ('San Fernando', '13650', 4);
Insert Into Municipality Values ('El Peñón', '25258', 11);
Insert Into Municipality Values ('Pamplonita', '54520', 18);
Insert Into Municipality Values ('San Juan Nepomuceno', '13657', 4);
Insert Into Municipality Values ('Miriti Paraná', '91460', 29);
Insert Into Municipality Values ('Támara', '85400', 26);
Insert Into Municipality Values ('Santa Catalina', '13673', 4);
Insert Into Municipality Values ('Santa Rosa', '13683', 4);
Insert Into Municipality Values ('Tibasosa', '15806', 5);
Insert Into Municipality Values ('Simití', '13744', 4);
Insert Into Municipality Values ('Soplaviento', '13760', 4);
Insert Into Municipality Values ('Talaigua Nuevo', '13780', 4);
Insert Into Municipality Values ('Tiquisio', '13810', 4);
Insert Into Municipality Values ('Turbaco', '13836', 4);
Insert Into Municipality Values ('Turbaná', '13838', 4);
Insert Into Municipality Values ('Villanueva', '13873', 4);
Insert Into Municipality Values ('Páez', '19517', 8);
Insert Into Municipality Values ('Tunja', '15001', 5);
Insert Into Municipality Values ('Almeida', '15022', 5);
Insert Into Municipality Values ('Aquitania', '15047', 5);
Insert Into Municipality Values ('Arcabuco', '15051', 5);
Insert Into Municipality Values ('Ibagué', '73001', 23);
Insert Into Municipality Values ('Berbeo', '15090', 5);
Insert Into Municipality Values ('Betéitiva', '15092', 5);
Insert Into Municipality Values ('Boavita', '15097', 5);
Insert Into Municipality Values ('Boyacá', '15104', 5);
Insert Into Municipality Values ('Briceño', '15106', 5);
Insert Into Municipality Values ('Buena Vista', '15109', 5);
Insert Into Municipality Values ('Busbanzá', '15114', 5);
Insert Into Municipality Values ('Caldas', '15131', 5);
Insert Into Municipality Values ('Campohermoso', '15135', 5);
Insert Into Municipality Values ('Cerinza', '15162', 5);
Insert Into Municipality Values ('Chinavita', '15172', 5);
Insert Into Municipality Values ('Chiquinquirá', '15176', 5);
Insert Into Municipality Values ('Chiscas', '15180', 5);
Insert Into Municipality Values ('Chita', '15183', 5);
Insert Into Municipality Values ('Chitaraque', '15185', 5);
Insert Into Municipality Values ('Chivatá', '15187', 5);
Insert Into Municipality Values ('Cómbita', '15204', 5);
Insert Into Municipality Values ('Coper', '15212', 5);
Insert Into Municipality Values ('Corrales', '15215', 5);
Insert Into Municipality Values ('Covarachía', '15218', 5);
Insert Into Municipality Values ('Cubará', '15223', 5);
Insert Into Municipality Values ('Cucaita', '15224', 5);
Insert Into Municipality Values ('Cuítiva', '15226', 5);
Insert Into Municipality Values ('Chíquiza', '15232', 5);
Insert Into Municipality Values ('Chivor', '15236', 5);
Insert Into Municipality Values ('Duitama', '15238', 5);
Insert Into Municipality Values ('El Cocuy', '15244', 5);
Insert Into Municipality Values ('El Espino', '15248', 5);
Insert Into Municipality Values ('Firavitoba', '15272', 5);
Insert Into Municipality Values ('Floresta', '15276', 5);
Insert Into Municipality Values ('Gachantivá', '15293', 5);
Insert Into Municipality Values ('Gameza', '15296', 5);
Insert Into Municipality Values ('Garagoa', '15299', 5);
Insert Into Municipality Values ('Guacamayas', '15317', 5);
Insert Into Municipality Values ('Guateque', '15322', 5);
Insert Into Municipality Values ('Guayatá', '15325', 5);
Insert Into Municipality Values ('Güicán', '15332', 5);
Insert Into Municipality Values ('Iza', '15362', 5);
Insert Into Municipality Values ('Jenesano', '15367', 5);
Insert Into Municipality Values ('Jericó', '15368', 5);
Insert Into Municipality Values ('Labranzagrande', '15377', 5);
Insert Into Municipality Values ('La Capilla', '15380', 5);
Insert Into Municipality Values ('La Victoria', '15401', 5);
Insert Into Municipality Values ('Puerto Colombia', '8573', 2);
Insert Into Municipality Values ('Belén', '52083', 17);
Insert Into Municipality Values ('Macanal', '15425', 5);
Insert Into Municipality Values ('Maripí', '15442', 5);
Insert Into Municipality Values ('Miraflores', '15455', 5);
Insert Into Municipality Values ('Mongua', '15464', 5);
Insert Into Municipality Values ('Monguí', '15466', 5);
Insert Into Municipality Values ('Moniquirá', '15469', 5);
Insert Into Municipality Values ('Muzo', '15480', 5);
Insert Into Municipality Values ('Nobsa', '15491', 5);
Insert Into Municipality Values ('Nuevo Colón', '15494', 5);
Insert Into Municipality Values ('Oicatá', '15500', 5);
Insert Into Municipality Values ('Otanche', '15507', 5);
Insert Into Municipality Values ('Pachavita', '15511', 5);
Insert Into Municipality Values ('Páez', '15514', 5);
Insert Into Municipality Values ('Paipa', '15516', 5);
Insert Into Municipality Values ('Pajarito', '15518', 5);
Insert Into Municipality Values ('Panqueba', '15522', 5);
Insert Into Municipality Values ('Pauna', '15531', 5);
Insert Into Municipality Values ('Paya', '15533', 5);
Insert Into Municipality Values ('Sopó', '25758', 11);
Insert Into Municipality Values ('Pesca', '15542', 5);
Insert Into Municipality Values ('Pisba', '15550', 5);
Insert Into Municipality Values ('Puerto Boyacá', '15572', 5);
Insert Into Municipality Values ('Quípama', '15580', 5);
Insert Into Municipality Values ('Ramiriquí', '15599', 5);
Insert Into Municipality Values ('Ráquira', '15600', 5);
Insert Into Municipality Values ('Rondón', '15621', 5);
Insert Into Municipality Values ('Saboyá', '15632', 5);
Insert Into Municipality Values ('Sáchica', '15638', 5);
Insert Into Municipality Values ('Samacá', '15646', 5);
Insert Into Municipality Values ('San Eduardo', '15660', 5);
Insert Into Municipality Values ('Carmen del Darien', '27150', 12);
Insert Into Municipality Values ('Gama', '25299', 11);
Insert Into Municipality Values ('San Mateo', '15673', 5);
Insert Into Municipality Values ('Sasaima', '25718', 11);
Insert Into Municipality Values ('Chachagüí', '52240', 17);
Insert Into Municipality Values ('Santana', '15686', 5);
Insert Into Municipality Values ('Santa María', '15690', 5);
Insert Into Municipality Values ('Cúcuta', '54001', 18);
Insert Into Municipality Values ('Santa Sofía', '15696', 5);
Insert Into Municipality Values ('Sativanorte', '15720', 5);
Insert Into Municipality Values ('Sativasur', '15723', 5);
Insert Into Municipality Values ('Siachoque', '15740', 5);
Insert Into Municipality Values ('Soatá', '15753', 5);
Insert Into Municipality Values ('Socotá', '15755', 5);
Insert Into Municipality Values ('Socha', '15757', 5);
Insert Into Municipality Values ('Sogamoso', '15759', 5);
Insert Into Municipality Values ('Somondoco', '15761', 5);
Insert Into Municipality Values ('Sora', '15762', 5);
Insert Into Municipality Values ('Sotaquirá', '15763', 5);
Insert Into Municipality Values ('Soracá', '15764', 5);
Insert Into Municipality Values ('Susacón', '15774', 5);
Insert Into Municipality Values ('Sutamarchán', '15776', 5);
Insert Into Municipality Values ('Sutatenza', '15778', 5);
Insert Into Municipality Values ('Tasco', '15790', 5);
Insert Into Municipality Values ('Tenza', '15798', 5);
Insert Into Municipality Values ('Tibaná', '15804', 5);
Insert Into Municipality Values ('Tinjacá', '15808', 5);
Insert Into Municipality Values ('Tipacoque', '15810', 5);
Insert Into Municipality Values ('Toca', '15814', 5);
Insert Into Municipality Values ('Cartagena', '13001', 4);
Insert Into Municipality Values ('Tópaga', '15820', 5);
Insert Into Municipality Values ('Tota', '15822', 5);
Insert Into Municipality Values ('Turmequé', '15835', 5);
Insert Into Municipality Values ('Granada', '5313', 1);
Insert Into Municipality Values ('Tutazá', '15839', 5);
Insert Into Municipality Values ('Umbita', '15842', 5);
Insert Into Municipality Values ('Ventaquemada', '15861', 5);
Insert Into Municipality Values ('Viracachá', '15879', 5);
Insert Into Municipality Values ('Zetaquira', '15897', 5);
Insert Into Municipality Values ('Manizales', '17001', 6);
Insert Into Municipality Values ('Aguadas', '17013', 6);
Insert Into Municipality Values ('Anserma', '17042', 6);
Insert Into Municipality Values ('Aranzazu', '17050', 6);
Insert Into Municipality Values ('Belalcázar', '17088', 6);
Insert Into Municipality Values ('Chinchiná', '17174', 6);
Insert Into Municipality Values ('Filadelfia', '17272', 6);
Insert Into Municipality Values ('La Dorada', '17380', 6);
Insert Into Municipality Values ('La Merced', '17388', 6);
Insert Into Municipality Values ('Manzanares', '17433', 6);
Insert Into Municipality Values ('Marmato', '17442', 6);
Insert Into Municipality Values ('Marulanda', '17446', 6);
Insert Into Municipality Values ('Neira', '17486', 6);
Insert Into Municipality Values ('Norcasia', '17495', 6);
Insert Into Municipality Values ('Pácora', '17513', 6);
Insert Into Municipality Values ('Palestina', '17524', 6);
Insert Into Municipality Values ('Pensilvania', '17541', 6);
Insert Into Municipality Values ('Riosucio', '17614', 6);
Insert Into Municipality Values ('Risaralda', '17616', 6);
Insert Into Municipality Values ('Salamina', '17653', 6);
Insert Into Municipality Values ('Samaná', '17662', 6);
Insert Into Municipality Values ('San José', '17665', 6);
Insert Into Municipality Values ('Supía', '17777', 6);
Insert Into Municipality Values ('Victoria', '17867', 6);
Insert Into Municipality Values ('Villamaría', '17873', 6);
Insert Into Municipality Values ('Viterbo', '17877', 6);
Insert Into Municipality Values ('Florencia', '18001', 7);
Insert Into Municipality Values ('Albania', '18029', 7);
Insert Into Municipality Values ('Santa Bárbara de Pinto', '47720', 15);
Insert Into Municipality Values ('María la Baja', '13442', 4);
Insert Into Municipality Values ('Curillo', '18205', 7);
Insert Into Municipality Values ('El Doncello', '18247', 7);
Insert Into Municipality Values ('El Paujil', '18256', 7);
Insert Into Municipality Values ('Morelia', '18479', 7);
Insert Into Municipality Values ('Puerto Rico', '18592', 7);
Insert Into Municipality Values ('La Montañita', '18410', 7);
Insert Into Municipality Values ('San Vicente del Caguán', '18753', 7);
Insert Into Municipality Values ('Solano', '18756', 7);
Insert Into Municipality Values ('Solita', '18785', 7);
Insert Into Municipality Values ('Valparaíso', '18860', 7);
Insert Into Municipality Values ('Popayán', '19001', 8);
Insert Into Municipality Values ('Almaguer', '19022', 8);
Insert Into Municipality Values ('Argelia', '19050', 8);
Insert Into Municipality Values ('Balboa', '19075', 8);
Insert Into Municipality Values ('Bolívar', '19100', 8);
Insert Into Municipality Values ('Buenos Aires', '19110', 8);
Insert Into Municipality Values ('Cajibío', '19130', 8);
Insert Into Municipality Values ('Caldono', '19137', 8);
Insert Into Municipality Values ('Caloto', '19142', 8);
Insert Into Municipality Values ('Corinto', '19212', 8);
Insert Into Municipality Values ('El Tambo', '19256', 8);
Insert Into Municipality Values ('Florencia', '19290', 8);
Insert Into Municipality Values ('Guachené', '19300', 8);
Insert Into Municipality Values ('Guapi', '19318', 8);
Insert Into Municipality Values ('Inzá', '19355', 8);
Insert Into Municipality Values ('Jambaló', '19364', 8);
Insert Into Municipality Values ('La Sierra', '19392', 8);
Insert Into Municipality Values ('La Vega', '19397', 8);
Insert Into Municipality Values ('López', '19418', 8);
Insert Into Municipality Values ('Mercaderes', '19450', 8);
Insert Into Municipality Values ('Miranda', '19455', 8);
Insert Into Municipality Values ('Morales', '19473', 8);
Insert Into Municipality Values ('Padilla', '19513', 8);
Insert Into Municipality Values ('Patía', '19532', 8);
Insert Into Municipality Values ('Piamonte', '19533', 8);
Insert Into Municipality Values ('Piendamó', '19548', 8);
Insert Into Municipality Values ('Puerto Tejada', '19573', 8);
Insert Into Municipality Values ('Puracé', '19585', 8);
Insert Into Municipality Values ('Rosas', '19622', 8);
Insert Into Municipality Values ('El Peñón', '68250', 21);
Insert Into Municipality Values ('Jardín', '5364', 1);
Insert Into Municipality Values ('Santa Rosa', '19701', 8);
Insert Into Municipality Values ('Silvia', '19743', 8);
Insert Into Municipality Values ('Sotara', '19760', 8);
Insert Into Municipality Values ('Suárez', '19780', 8);
Insert Into Municipality Values ('Sucre', '19785', 8);
Insert Into Municipality Values ('Timbío', '19807', 8);
Insert Into Municipality Values ('Timbiquí', '19809', 8);
Insert Into Municipality Values ('Toribio', '19821', 8);
Insert Into Municipality Values ('Totoró', '19824', 8);
Insert Into Municipality Values ('Villa Rica', '19845', 8);
Insert Into Municipality Values ('Valledupar', '20001', 9);
Insert Into Municipality Values ('Aguachica', '20011', 9);
Insert Into Municipality Values ('Agustín Codazzi', '20013', 9);
Insert Into Municipality Values ('Astrea', '20032', 9);
Insert Into Municipality Values ('Becerril', '20045', 9);
Insert Into Municipality Values ('Bosconia', '20060', 9);
Insert Into Municipality Values ('Chimichagua', '20175', 9);
Insert Into Municipality Values ('Chiriguaná', '20178', 9);
Insert Into Municipality Values ('Curumaní', '20228', 9);
Insert Into Municipality Values ('El Copey', '20238', 9);
Insert Into Municipality Values ('El Paso', '20250', 9);
Insert Into Municipality Values ('Gamarra', '20295', 9);
Insert Into Municipality Values ('González', '20310', 9);
Insert Into Municipality Values ('La Gloria', '20383', 9);
Insert Into Municipality Values ('Jamundí', '76364', 24);
Insert Into Municipality Values ('Manaure', '20443', 9);
Insert Into Municipality Values ('Pailitas', '20517', 9);
Insert Into Municipality Values ('Pelaya', '20550', 9);
Insert Into Municipality Values ('Pueblo Bello', '20570', 9);
Insert Into Municipality Values ('Tadó', '27787', 12);
Insert Into Municipality Values ('La Paz', '20621', 9);
Insert Into Municipality Values ('San Alberto', '20710', 9);
Insert Into Municipality Values ('San Diego', '20750', 9);
Insert Into Municipality Values ('San Martín', '20770', 9);
Insert Into Municipality Values ('Tamalameque', '20787', 9);
Insert Into Municipality Values ('Montería', '23001', 10);
Insert Into Municipality Values ('Ayapel', '23068', 10);
Insert Into Municipality Values ('Buenavista', '23079', 10);
Insert Into Municipality Values ('Canalete', '23090', 10);
Insert Into Municipality Values ('Cereté', '23162', 10);
Insert Into Municipality Values ('Chimá', '23168', 10);
Insert Into Municipality Values ('Chinú', '23182', 10);
Insert Into Municipality Values ('Orocué', '85230', 26);
Insert Into Municipality Values ('Cotorra', '23300', 10);
Insert Into Municipality Values ('Líbano', '73411', 23);
Insert Into Municipality Values ('Lorica', '23417', 10);
Insert Into Municipality Values ('Los Córdobas', '23419', 10);
Insert Into Municipality Values ('Momil', '23464', 10);
Insert Into Municipality Values ('Moñitos', '23500', 10);
Insert Into Municipality Values ('Planeta Rica', '23555', 10);
Insert Into Municipality Values ('Pueblo Nuevo', '23570', 10);
Insert Into Municipality Values ('Puerto Escondido', '23574', 10);
Insert Into Municipality Values ('Yacopí', '25885', 11);
Insert Into Municipality Values ('Purísima', '23586', 10);
Insert Into Municipality Values ('Sahagún', '23660', 10);
Insert Into Municipality Values ('San Andrés Sotavento', '23670', 10);
Insert Into Municipality Values ('San Antero', '23672', 10);
Insert Into Municipality Values ('Calarcá', '63130', 19);
Insert Into Municipality Values ('Sonsón', '5756', 1);
Insert Into Municipality Values ('El Carmen', '54245', 18);
Insert Into Municipality Values ('San Pelayo', '23686', 10);
Insert Into Municipality Values ('Tierralta', '23807', 10);
Insert Into Municipality Values ('Tuchín', '23815', 10);
Insert Into Municipality Values ('Valencia', '23855', 10);
Insert Into Municipality Values ('Lérida', '73408', 23);
Insert Into Municipality Values ('Anapoima', '25035', 11);
Insert Into Municipality Values ('Arbeláez', '25053', 11);
Insert Into Municipality Values ('Beltrán', '25086', 11);
Insert Into Municipality Values ('Bituima', '25095', 11);
Insert Into Municipality Values ('Bojacá', '25099', 11);
Insert Into Municipality Values ('Cabrera', '25120', 11);
Insert Into Municipality Values ('Cachipay', '25123', 11);
Insert Into Municipality Values ('Cajicá', '25126', 11);
Insert Into Municipality Values ('Caparrapí', '25148', 11);
Insert Into Municipality Values ('Caqueza', '25151', 11);
Insert Into Municipality Values ('La Apartada', '23350', 10);
Insert Into Municipality Values ('Chaguaní', '25168', 11);
Insert Into Municipality Values ('Chipaque', '25178', 11);
Insert Into Municipality Values ('Choachí', '25181', 11);
Insert Into Municipality Values ('Chocontá', '25183', 11);
Insert Into Municipality Values ('Cogua', '25200', 11);
Insert Into Municipality Values ('Cota', '25214', 11);
Insert Into Municipality Values ('Cucunubá', '25224', 11);
Insert Into Municipality Values ('El Colegio', '25245', 11);
Insert Into Municipality Values ('El Rosal', '25260', 11);
Insert Into Municipality Values ('Fomeque', '25279', 11);
Insert Into Municipality Values ('Fosca', '25281', 11);
Insert Into Municipality Values ('Funza', '25286', 11);
Insert Into Municipality Values ('Fúquene', '25288', 11);
Insert Into Municipality Values ('Gachala', '25293', 11);
Insert Into Municipality Values ('Gachancipá', '25295', 11);
Insert Into Municipality Values ('Gachetá', '25297', 11);
Insert Into Municipality Values ('San Cristóbal', '13620', 4);
Insert Into Municipality Values ('Girardot', '25307', 11);
Insert Into Municipality Values ('Granada', '25312', 11);
Insert Into Municipality Values ('Guachetá', '25317', 11);
Insert Into Municipality Values ('Guaduas', '25320', 11);
Insert Into Municipality Values ('Guasca', '25322', 11);
Insert Into Municipality Values ('Guataquí', '25324', 11);
Insert Into Municipality Values ('Guatavita', '25326', 11);
Insert Into Municipality Values ('Fusagasugá', '25290', 11);
Insert Into Municipality Values ('Guayabetal', '25335', 11);
Insert Into Municipality Values ('Gutiérrez', '25339', 11);
Insert Into Municipality Values ('Jerusalén', '25368', 11);
Insert Into Municipality Values ('Junín', '25372', 11);
Insert Into Municipality Values ('La Calera', '25377', 11);
Insert Into Municipality Values ('La Mesa', '25386', 11);
Insert Into Municipality Values ('La Palma', '25394', 11);
Insert Into Municipality Values ('La Peña', '25398', 11);
Insert Into Municipality Values ('La Vega', '25402', 11);
Insert Into Municipality Values ('Lenguazaque', '25407', 11);
Insert Into Municipality Values ('Macheta', '25426', 11);
Insert Into Municipality Values ('Madrid', '25430', 11);
Insert Into Municipality Values ('Manta', '25436', 11);
Insert Into Municipality Values ('Medina', '25438', 11);
Insert Into Municipality Values ('Mosquera', '25473', 11);
Insert Into Municipality Values ('Nariño', '25483', 11);
Insert Into Municipality Values ('Nemocón', '25486', 11);
Insert Into Municipality Values ('Nilo', '25488', 11);
Insert Into Municipality Values ('Nimaima', '25489', 11);
Insert Into Municipality Values ('Nocaima', '25491', 11);
Insert Into Municipality Values ('Venecia', '25506', 11);
Insert Into Municipality Values ('Pacho', '25513', 11);
Insert Into Municipality Values ('Paime', '25518', 11);
Insert Into Municipality Values ('Pandi', '25524', 11);
Insert Into Municipality Values ('Paratebueno', '25530', 11);
Insert Into Municipality Values ('Pasca', '25535', 11);
Insert Into Municipality Values ('Puerto Salgar', '25572', 11);
Insert Into Municipality Values ('Pulí', '25580', 11);
Insert Into Municipality Values ('Quebradanegra', '25592', 11);
Insert Into Municipality Values ('Quetame', '25594', 11);
Insert Into Municipality Values ('Quipile', '25596', 11);
Insert Into Municipality Values ('Apulo', '25599', 11);
Insert Into Municipality Values ('Ricaurte', '25612', 11);
Insert Into Municipality Values ('Zambrano', '13894', 4);
Insert Into Municipality Values ('San Bernardo', '25649', 11);
Insert Into Municipality Values ('San Cayetano', '25653', 11);
Insert Into Municipality Values ('San Francisco', '25658', 11);
Insert Into Municipality Values ('La Uvita', '15403', 5);
Insert Into Municipality Values ('Zipaquirá', '25899', 11);
Insert Into Municipality Values ('Sesquilé', '25736', 11);
Insert Into Municipality Values ('Sibaté', '25740', 11);
Insert Into Municipality Values ('Silvania', '25743', 11);
Insert Into Municipality Values ('Simijaca', '25745', 11);
Insert Into Municipality Values ('Soacha', '25754', 11);
Insert Into Municipality Values ('Subachoque', '25769', 11);
Insert Into Municipality Values ('Suesca', '25772', 11);
Insert Into Municipality Values ('Supatá', '25777', 11);
Insert Into Municipality Values ('Susa', '25779', 11);
Insert Into Municipality Values ('Sutatausa', '25781', 11);
Insert Into Municipality Values ('Tabio', '25785', 11);
Insert Into Municipality Values ('Génova', '63302', 19);
Insert Into Municipality Values ('Tausa', '25793', 11);
Insert Into Municipality Values ('Tena', '25797', 11);
Insert Into Municipality Values ('Tenjo', '25799', 11);
Insert Into Municipality Values ('Tibacuy', '25805', 11);
Insert Into Municipality Values ('Tibirita', '25807', 11);
Insert Into Municipality Values ('Tocaima', '25815', 11);
Insert Into Municipality Values ('Tocancipá', '25817', 11);
Insert Into Municipality Values ('Topaipí', '25823', 11);
Insert Into Municipality Values ('Ubalá', '25839', 11);
Insert Into Municipality Values ('Ubaque', '25841', 11);
Insert Into Municipality Values ('Suárez', '73770', 23);
Insert Into Municipality Values ('Une', '25845', 11);
Insert Into Municipality Values ('Útica', '25851', 11);
Insert Into Municipality Values ('Castilla la Nueva', '50150', 16);
Insert Into Municipality Values ('Vianí', '25867', 11);
Insert Into Municipality Values ('Villagómez', '25871', 11);
Insert Into Municipality Values ('Villapinzón', '25873', 11);
Insert Into Municipality Values ('Villeta', '25875', 11);
Insert Into Municipality Values ('Viotá', '25878', 11);
Insert Into Municipality Values ('Zipacón', '25898', 11);
Insert Into Municipality Values ('Quibdó', '27001', 12);
Insert Into Municipality Values ('Acandí', '27006', 12);
Insert Into Municipality Values ('Alto Baudo', '27025', 12);
Insert Into Municipality Values ('Atrato', '27050', 12);
Insert Into Municipality Values ('Bagadó', '27073', 12);
Insert Into Municipality Values ('Bahía Solano', '27075', 12);
Insert Into Municipality Values ('Bajo Baudó', '27077', 12);
Insert Into Municipality Values ('Belén', '15087', 5);
Insert Into Municipality Values ('Bojaya', '27099', 12);
Insert Into Municipality Values ('Unión Panamericana', '27810', 12);
Insert Into Municipality Values ('Pueblo Viejo', '47570', 15);
Insert Into Municipality Values ('Cértegui', '27160', 12);
Insert Into Municipality Values ('Condoto', '27205', 12);
Insert Into Municipality Values ('Villagarzón', '86885', 27);
Insert Into Municipality Values ('Facatativá', '25269', 11);
Insert Into Municipality Values ('Juradó', '27372', 12);
Insert Into Municipality Values ('Lloró', '27413', 12);
Insert Into Municipality Values ('Medio Atrato', '27425', 12);
Insert Into Municipality Values ('Medio Baudó', '27430', 12);
Insert Into Municipality Values ('Medio San Juan', '27450', 12);
Insert Into Municipality Values ('Nóvita', '27491', 12);
Insert Into Municipality Values ('Nuquí', '27495', 12);
Insert Into Municipality Values ('Río Iro', '27580', 12);
Insert Into Municipality Values ('Río Quito', '27600', 12);
Insert Into Municipality Values ('Riosucio', '27615', 12);
Insert Into Municipality Values ('Puerto Libertador', '23580', 10);
Insert Into Municipality Values ('Sipí', '27745', 12);
Insert Into Municipality Values ('Unguía', '27800', 12);
Insert Into Municipality Values ('Neiva', '41001', 13);
Insert Into Municipality Values ('Acevedo', '41006', 13);
Insert Into Municipality Values ('Agrado', '41013', 13);
Insert Into Municipality Values ('Aipe', '41016', 13);
Insert Into Municipality Values ('Algeciras', '41020', 13);
Insert Into Municipality Values ('Altamira', '41026', 13);
Insert Into Municipality Values ('Baraya', '41078', 13);
Insert Into Municipality Values ('Campoalegre', '41132', 13);
Insert Into Municipality Values ('Colombia', '41206', 13);
Insert Into Municipality Values ('Elías', '41244', 13);
Insert Into Municipality Values ('Garzón', '41298', 13);
Insert Into Municipality Values ('Gigante', '41306', 13);
Insert Into Municipality Values ('Guadalupe', '41319', 13);
Insert Into Municipality Values ('Hobo', '41349', 13);
Insert Into Municipality Values ('Iquira', '41357', 13);
Insert Into Municipality Values ('Isnos', '41359', 13);
Insert Into Municipality Values ('La Argentina', '41378', 13);
Insert Into Municipality Values ('La Plata', '41396', 13);
Insert Into Municipality Values ('Marquetalia', '17444', 6);
Insert Into Municipality Values ('Nátaga', '41483', 13);
Insert Into Municipality Values ('Oporapa', '41503', 13);
Insert Into Municipality Values ('Paicol', '41518', 13);
Insert Into Municipality Values ('Palermo', '41524', 13);
Insert Into Municipality Values ('Palestina', '41530', 13);
Insert Into Municipality Values ('Pital', '41548', 13);
Insert Into Municipality Values ('Pitalito', '41551', 13);
Insert Into Municipality Values ('Rivera', '41615', 13);
Insert Into Municipality Values ('Saladoblanco', '41660', 13);
Insert Into Municipality Values ('Arboleda', '52051', 17);
Insert Into Municipality Values ('Santa María', '41676', 13);
Insert Into Municipality Values ('Suaza', '41770', 13);
Insert Into Municipality Values ('Tarqui', '41791', 13);
Insert Into Municipality Values ('Tesalia', '41797', 13);
Insert Into Municipality Values ('Tello', '41799', 13);
Insert Into Municipality Values ('Teruel', '41801', 13);
Insert Into Municipality Values ('Timaná', '41807', 13);
Insert Into Municipality Values ('Villavieja', '41872', 13);
Insert Into Municipality Values ('Yaguará', '41885', 13);
Insert Into Municipality Values ('Riohacha', '44001', 14);
Insert Into Municipality Values ('Albania', '44035', 14);
Insert Into Municipality Values ('Barrancas', '44078', 14);
Insert Into Municipality Values ('Dibula', '44090', 14);
Insert Into Municipality Values ('Distracción', '44098', 14);
Insert Into Municipality Values ('El Molino', '44110', 14);
Insert Into Municipality Values ('Fonseca', '44279', 14);
Insert Into Municipality Values ('Hatonuevo', '44378', 14);
Insert Into Municipality Values ('Maicao', '44430', 14);
Insert Into Municipality Values ('Manaure', '44560', 14);
Insert Into Municipality Values ('Uribia', '44847', 14);
Insert Into Municipality Values ('Urumita', '44855', 14);
Insert Into Municipality Values ('Villanueva', '44874', 14);
Insert Into Municipality Values ('Santa Marta', '47001', 15);
Insert Into Municipality Values ('Algarrobo', '47030', 15);
Insert Into Municipality Values ('Aracataca', '47053', 15);
Insert Into Municipality Values ('Ariguaní', '47058', 15);
Insert Into Municipality Values ('Cerro San Antonio', '47161', 15);
Insert Into Municipality Values ('Chivolo', '47170', 15);
Insert Into Municipality Values ('Concordia', '47205', 15);
Insert Into Municipality Values ('El Banco', '47245', 15);
Insert Into Municipality Values ('El Piñon', '47258', 15);
Insert Into Municipality Values ('El Retén', '47268', 15);
Insert Into Municipality Values ('Fundación', '47288', 15);
Insert Into Municipality Values ('Guamal', '47318', 15);
Insert Into Municipality Values ('Nueva Granada', '47460', 15);
Insert Into Municipality Values ('Pedraza', '47541', 15);
Insert Into Municipality Values ('Pivijay', '47551', 15);
Insert Into Municipality Values ('Plato', '47555', 15);
Insert Into Municipality Values ('Remolino', '47605', 15);
Insert Into Municipality Values ('Salamina', '47675', 15);
Insert Into Municipality Values ('San Zenón', '47703', 15);
Insert Into Municipality Values ('Santa Ana', '47707', 15);
Insert Into Municipality Values ('Sitionuevo', '47745', 15);
Insert Into Municipality Values ('Tenerife', '47798', 15);
Insert Into Municipality Values ('Zapayán', '47960', 15);
Insert Into Municipality Values ('Zona Bananera', '47980', 15);
Insert Into Municipality Values ('Villavicencio', '50001', 16);
Insert Into Municipality Values ('Acacias', '50006', 16);
Insert Into Municipality Values ('Cabuyaro', '50124', 16);
Insert Into Municipality Values ('Cubarral', '50223', 16);
Insert Into Municipality Values ('Cumaral', '50226', 16);
Insert Into Municipality Values ('El Calvario', '50245', 16);
Insert Into Municipality Values ('El Castillo', '50251', 16);
Insert Into Municipality Values ('El Dorado', '50270', 16);
Insert Into Municipality Values ('Buenaventura', '76109', 24);
Insert Into Municipality Values ('Granada', '50313', 16);
Insert Into Municipality Values ('Guamal', '50318', 16);
Insert Into Municipality Values ('Mapiripán', '50325', 16);
Insert Into Municipality Values ('Mesetas', '50330', 16);
Insert Into Municipality Values ('La Macarena', '50350', 16);
Insert Into Municipality Values ('Uribe', '50370', 16);
Insert Into Municipality Values ('Lejanías', '50400', 16);
Insert Into Municipality Values ('Puerto Concordia', '50450', 16);
Insert Into Municipality Values ('Puerto Gaitán', '50568', 16);
Insert Into Municipality Values ('Puerto López', '50573', 16);
Insert Into Municipality Values ('Puerto Lleras', '50577', 16);
Insert Into Municipality Values ('Puerto Rico', '50590', 16);
Insert Into Municipality Values ('Restrepo', '50606', 16);
Insert Into Municipality Values ('Ciénaga', '47189', 15);
Insert Into Municipality Values ('Ponedera', '8560', 2);
Insert Into Municipality Values ('San Juanito', '50686', 16);
Insert Into Municipality Values ('San Martín', '50689', 16);
Insert Into Municipality Values ('Vista Hermosa', '50711', 16);
Insert Into Municipality Values ('Pasto', '52001', 17);
Insert Into Municipality Values ('Albán', '52019', 17);
Insert Into Municipality Values ('Aldana', '52022', 17);
Insert Into Municipality Values ('Ancuyá', '52036', 17);
Insert Into Municipality Values ('Tununguá', '15832', 5);
Insert Into Municipality Values ('Barbacoas', '52079', 17);
Insert Into Municipality Values ('Motavita', '15476', 5);
Insert Into Municipality Values ('San Bernardo del Viento', '23675', 10);
Insert Into Municipality Values ('Colón', '52203', 17);
Insert Into Municipality Values ('Consaca', '52207', 17);
Insert Into Municipality Values ('Contadero', '52210', 17);
Insert Into Municipality Values ('Córdoba', '52215', 17);
Insert Into Municipality Values ('Cuaspud', '52224', 17);
Insert Into Municipality Values ('Cumbal', '52227', 17);
Insert Into Municipality Values ('Cumbitara', '52233', 17);
Insert Into Municipality Values ('El Charco', '52250', 17);
Insert Into Municipality Values ('El Peñol', '52254', 17);
Insert Into Municipality Values ('El Rosario', '52256', 17);
Insert Into Municipality Values ('Istmina', '27361', 12);
Insert Into Municipality Values ('El Tambo', '52260', 17);
Insert Into Municipality Values ('Funes', '52287', 17);
Insert Into Municipality Values ('Guachucal', '52317', 17);
Insert Into Municipality Values ('Guaitarilla', '52320', 17);
Insert Into Municipality Values ('Gualmatán', '52323', 17);
Insert Into Municipality Values ('Iles', '52352', 17);
Insert Into Municipality Values ('Imués', '52354', 17);
Insert Into Municipality Values ('Ipiales', '52356', 17);
Insert Into Municipality Values ('La Cruz', '52378', 17);
Insert Into Municipality Values ('La Florida', '52381', 17);
Insert Into Municipality Values ('La Llanada', '52385', 17);
Insert Into Municipality Values ('La Tola', '52390', 17);
Insert Into Municipality Values ('La Unión', '52399', 17);
Insert Into Municipality Values ('Leiva', '52405', 17);
Insert Into Municipality Values ('Linares', '52411', 17);
Insert Into Municipality Values ('Los Andes', '52418', 17);
Insert Into Municipality Values ('Magüí', '52427', 17);
Insert Into Municipality Values ('Mallama', '52435', 17);
Insert Into Municipality Values ('Mosquera', '52473', 17);
Insert Into Municipality Values ('Nariño', '52480', 17);
Insert Into Municipality Values ('Olaya Herrera', '52490', 17);
Insert Into Municipality Values ('Ospina', '52506', 17);
Insert Into Municipality Values ('Francisco Pizarro', '52520', 17);
Insert Into Municipality Values ('Policarpa', '52540', 17);
Insert Into Municipality Values ('Potosí', '52560', 17);
Insert Into Municipality Values ('Providencia', '52565', 17);
Insert Into Municipality Values ('Puerres', '52573', 17);
Insert Into Municipality Values ('Pupiales', '52585', 17);
Insert Into Municipality Values ('Ricaurte', '52612', 17);
Insert Into Municipality Values ('Roberto Payán', '52621', 17);
Insert Into Municipality Values ('Samaniego', '52678', 17);
Insert Into Municipality Values ('Sandoná', '52683', 17);
Insert Into Municipality Values ('San Bernardo', '52685', 17);
Insert Into Municipality Values ('San Lorenzo', '52687', 17);
Insert Into Municipality Values ('San Pablo', '52693', 17);
Insert Into Municipality Values ('Belmira', '5086', 1);
Insert Into Municipality Values ('Ciénega', '15189', 5);
Insert Into Municipality Values ('Santa Bárbara', '52696', 17);
Insert Into Municipality Values ('Sapuyes', '52720', 17);
Insert Into Municipality Values ('Taminango', '52786', 17);
Insert Into Municipality Values ('Tangua', '52788', 17);
Insert Into Municipality Values ('Santacruz', '52699', 17);
Insert Into Municipality Values ('Túquerres', '52838', 17);
Insert Into Municipality Values ('Yacuanquer', '52885', 17);
Insert Into Municipality Values ('Puerto Wilches', '68575', 21);
Insert Into Municipality Values ('Puerto Parra', '68573', 21);
Insert Into Municipality Values ('Armenia', '63001', 19);
Insert Into Municipality Values ('Buenavista', '63111', 19);
Insert Into Municipality Values ('Circasia', '63190', 19);
Insert Into Municipality Values ('Córdoba', '63212', 19);
Insert Into Municipality Values ('Filandia', '63272', 19);
Insert Into Municipality Values ('La Tebaida', '63401', 19);
Insert Into Municipality Values ('Montenegro', '63470', 19);
Insert Into Municipality Values ('Pijao', '63548', 19);
Insert Into Municipality Values ('Quimbaya', '63594', 19);
Insert Into Municipality Values ('Salento', '63690', 19);
Insert Into Municipality Values ('Pereira', '66001', 20);
Insert Into Municipality Values ('Apía', '66045', 20);
Insert Into Municipality Values ('Balboa', '66075', 20);
Insert Into Municipality Values ('Dosquebradas', '66170', 20);
Insert Into Municipality Values ('Guática', '66318', 20);
Insert Into Municipality Values ('La Celia', '66383', 20);
Insert Into Municipality Values ('La Virginia', '66400', 20);
Insert Into Municipality Values ('Marsella', '66440', 20);
Insert Into Municipality Values ('Mistrató', '66456', 20);
Insert Into Municipality Values ('Pueblo Rico', '66572', 20);
Insert Into Municipality Values ('Quinchía', '66594', 20);
Insert Into Municipality Values ('Santuario', '66687', 20);
Insert Into Municipality Values ('Bucaramanga', '68001', 21);
Insert Into Municipality Values ('Aguada', '68013', 21);
Insert Into Municipality Values ('Albania', '68020', 21);
Insert Into Municipality Values ('Aratoca', '68051', 21);
Insert Into Municipality Values ('Barbosa', '68077', 21);
Insert Into Municipality Values ('Barichara', '68079', 21);
Insert Into Municipality Values ('Barrancabermeja', '68081', 21);
Insert Into Municipality Values ('Betulia', '68092', 21);
Insert Into Municipality Values ('Bolívar', '68101', 21);
Insert Into Municipality Values ('Cabrera', '68121', 21);
Insert Into Municipality Values ('California', '68132', 21);
Insert Into Municipality Values ('Carcasí', '68152', 21);
Insert Into Municipality Values ('Cepitá', '68160', 21);
Insert Into Municipality Values ('Cerrito', '68162', 21);
Insert Into Municipality Values ('Charalá', '68167', 21);
Insert Into Municipality Values ('Charta', '68169', 21);
Insert Into Municipality Values ('Chipatá', '68179', 21);
Insert Into Municipality Values ('Cimitarra', '68190', 21);
Insert Into Municipality Values ('Concepción', '68207', 21);
Insert Into Municipality Values ('Confines', '68209', 21);
Insert Into Municipality Values ('Contratación', '68211', 21);
Insert Into Municipality Values ('Coromoro', '68217', 21);
Insert Into Municipality Values ('Curití', '68229', 21);
Insert Into Municipality Values ('El Guacamayo', '68245', 21);
Insert Into Municipality Values ('El Playón', '68255', 21);
Insert Into Municipality Values ('Encino', '68264', 21);
Insert Into Municipality Values ('Enciso', '68266', 21);
Insert Into Municipality Values ('Florián', '68271', 21);
Insert Into Municipality Values ('Floridablanca', '68276', 21);
Insert Into Municipality Values ('Galán', '68296', 21);
Insert Into Municipality Values ('Gambita', '68298', 21);
Insert Into Municipality Values ('Girón', '68307', 21);
Insert Into Municipality Values ('Guaca', '68318', 21);
Insert Into Municipality Values ('Guadalupe', '68320', 21);
Insert Into Municipality Values ('Guapotá', '68322', 21);
Insert Into Municipality Values ('Guavatá', '68324', 21);
Insert Into Municipality Values ('Güepsa', '68327', 21);
Insert Into Municipality Values ('Jesús María', '68368', 21);
Insert Into Municipality Values ('Jordán', '68370', 21);
Insert Into Municipality Values ('La Belleza', '68377', 21);
Insert Into Municipality Values ('Landázuri', '68385', 21);
Insert Into Municipality Values ('La Paz', '68397', 21);
Insert Into Municipality Values ('Lebríja', '68406', 21);
Insert Into Municipality Values ('Los Santos', '68418', 21);
Insert Into Municipality Values ('Macaravita', '68425', 21);
Insert Into Municipality Values ('Málaga', '68432', 21);
Insert Into Municipality Values ('Matanza', '68444', 21);
Insert Into Municipality Values ('Mogotes', '68464', 21);
Insert Into Municipality Values ('Molagavita', '68468', 21);
Insert Into Municipality Values ('Ocamonte', '68498', 21);
Insert Into Municipality Values ('Oiba', '68500', 21);
Insert Into Municipality Values ('Onzaga', '68502', 21);
Insert Into Municipality Values ('Palmar', '68522', 21);
Insert Into Municipality Values ('Páramo', '68533', 21);
Insert Into Municipality Values ('Piedecuesta', '68547', 21);
Insert Into Municipality Values ('Pinchote', '68549', 21);
Insert Into Municipality Values ('Puente Nacional', '68572', 21);
Insert Into Municipality Values ('Rionegro', '68615', 21);
Insert Into Municipality Values ('San Andrés', '68669', 21);
Insert Into Municipality Values ('San Gil', '68679', 21);
Insert Into Municipality Values ('San Joaquín', '68682', 21);
Insert Into Municipality Values ('San Miguel', '68686', 21);
Insert Into Municipality Values ('Santa Bárbara', '68705', 21);
Insert Into Municipality Values ('Simacota', '68745', 21);
Insert Into Municipality Values ('Socorro', '68755', 21);
Insert Into Municipality Values ('Suaita', '68770', 21);
Insert Into Municipality Values ('Sucre', '68773', 21);
Insert Into Municipality Values ('Suratá', '68780', 21);
Insert Into Municipality Values ('Tona', '68820', 21);
Insert Into Municipality Values ('Vélez', '68861', 21);
Insert Into Municipality Values ('Vetas', '68867', 21);
Insert Into Municipality Values ('Villanueva', '68872', 21);
Insert Into Municipality Values ('Zapatoca', '68895', 21);
Insert Into Municipality Values ('Sincelejo', '70001', 22);
Insert Into Municipality Values ('Buenavista', '70110', 22);
Insert Into Municipality Values ('Caimito', '70124', 22);
Insert Into Municipality Values ('Coloso', '70204', 22);
Insert Into Municipality Values ('Coveñas', '70221', 22);
Insert Into Municipality Values ('Chalán', '70230', 22);
Insert Into Municipality Values ('El Roble', '70233', 22);
Insert Into Municipality Values ('Galeras', '70235', 22);
Insert Into Municipality Values ('Guaranda', '70265', 22);
Insert Into Municipality Values ('La Unión', '70400', 22);
Insert Into Municipality Values ('Los Palmitos', '70418', 22);
Insert Into Municipality Values ('Majagual', '70429', 22);
Insert Into Municipality Values ('Morroa', '70473', 22);
Insert Into Municipality Values ('Ovejas', '70508', 22);
Insert Into Municipality Values ('Palmito', '70523', 22);
Insert Into Municipality Values ('San Benito Abad', '70678', 22);
Insert Into Municipality Values ('San Marcos', '70708', 22);
Insert Into Municipality Values ('San Onofre', '70713', 22);
Insert Into Municipality Values ('San Pedro', '70717', 22);
Insert Into Municipality Values ('Sucre', '70771', 22);
Insert Into Municipality Values ('Tolú Viejo', '70823', 22);
Insert Into Municipality Values ('Alpujarra', '73024', 23);
Insert Into Municipality Values ('Alvarado', '73026', 23);
Insert Into Municipality Values ('Ambalema', '73030', 23);
Insert Into Municipality Values ('Armero', '73055', 23);
Insert Into Municipality Values ('Ataco', '73067', 23);
Insert Into Municipality Values ('Cajamarca', '73124', 23);
Insert Into Municipality Values ('Chaparral', '73168', 23);
Insert Into Municipality Values ('Coello', '73200', 23);
Insert Into Municipality Values ('Coyaima', '73217', 23);
Insert Into Municipality Values ('Cunday', '73226', 23);
Insert Into Municipality Values ('Dolores', '73236', 23);
Insert Into Municipality Values ('Espinal', '73268', 23);
Insert Into Municipality Values ('Falan', '73270', 23);
Insert Into Municipality Values ('Flandes', '73275', 23);
Insert Into Municipality Values ('Fresno', '73283', 23);
Insert Into Municipality Values ('Guamo', '73319', 23);
Insert Into Municipality Values ('Herveo', '73347', 23);
Insert Into Municipality Values ('Honda', '73349', 23);
Insert Into Municipality Values ('Icononzo', '73352', 23);
Insert Into Municipality Values ('Mariquita', '73443', 23);
Insert Into Municipality Values ('Melgar', '73449', 23);
Insert Into Municipality Values ('Murillo', '73461', 23);
Insert Into Municipality Values ('Natagaima', '73483', 23);
Insert Into Municipality Values ('Ortega', '73504', 23);
Insert Into Municipality Values ('Palocabildo', '73520', 23);
Insert Into Municipality Values ('Piedras', '73547', 23);
Insert Into Municipality Values ('Planadas', '73555', 23);
Insert Into Municipality Values ('Prado', '73563', 23);
Insert Into Municipality Values ('Purificación', '73585', 23);
Insert Into Municipality Values ('Rio Blanco', '73616', 23);
Insert Into Municipality Values ('Roncesvalles', '73622', 23);
Insert Into Municipality Values ('Rovira', '73624', 23);
Insert Into Municipality Values ('Saldaña', '73671', 23);
Insert Into Municipality Values ('Santa Isabel', '73686', 23);
Insert Into Municipality Values ('Venadillo', '73861', 23);
Insert Into Municipality Values ('Villahermosa', '73870', 23);
Insert Into Municipality Values ('Villarrica', '73873', 23);
Insert Into Municipality Values ('Arauquita', '81065', 25);
Insert Into Municipality Values ('Cravo Norte', '81220', 25);
Insert Into Municipality Values ('Fortul', '81300', 25);
Insert Into Municipality Values ('Puerto Rondón', '81591', 25);
Insert Into Municipality Values ('Saravena', '81736', 25);
Insert Into Municipality Values ('Tame', '81794', 25);
Insert Into Municipality Values ('Arauca', '81001', 25);
Insert Into Municipality Values ('Yopal', '85001', 26);
Insert Into Municipality Values ('Aguazul', '85010', 26);
Insert Into Municipality Values ('Chámeza', '85015', 26);
Insert Into Municipality Values ('Hato Corozal', '85125', 26);
Insert Into Municipality Values ('La Salina', '85136', 26);
Insert Into Municipality Values ('Monterrey', '85162', 26);
Insert Into Municipality Values ('Pore', '85263', 26);
Insert Into Municipality Values ('Recetor', '85279', 26);
Insert Into Municipality Values ('Sabanalarga', '85300', 26);
Insert Into Municipality Values ('Sácama', '85315', 26);
Insert Into Municipality Values ('Tauramena', '85410', 26);
Insert Into Municipality Values ('Trinidad', '85430', 26);
Insert Into Municipality Values ('Villanueva', '85440', 26);
Insert Into Municipality Values ('Mocoa', '86001', 27);
Insert Into Municipality Values ('Colón', '86219', 27);
Insert Into Municipality Values ('Orito', '86320', 27);
Insert Into Municipality Values ('Puerto Caicedo', '86569', 27);
Insert Into Municipality Values ('Puerto Guzmán', '86571', 27);
Insert Into Municipality Values ('Leguízamo', '86573', 27);
Insert Into Municipality Values ('Sibundoy', '86749', 27);
Insert Into Municipality Values ('San Francisco', '86755', 27);
Insert Into Municipality Values ('San Miguel', '86757', 27);
Insert Into Municipality Values ('Santiago', '86760', 27);
Insert Into Municipality Values ('Leticia', '91001', 29);
Insert Into Municipality Values ('El Encanto', '91263', 29);
Insert Into Municipality Values ('La Chorrera', '91405', 29);
Insert Into Municipality Values ('La Pedrera', '91407', 29);
Insert Into Municipality Values ('La Victoria', '91430', 29);
Insert Into Municipality Values ('Puerto Arica', '91536', 29);
Insert Into Municipality Values ('Puerto Nariño', '91540', 29);
Insert Into Municipality Values ('Puerto Santander', '91669', 29);
Insert Into Municipality Values ('Tarapacá', '91798', 29);
Insert Into Municipality Values ('Inírida', '94001', 30);
Insert Into Municipality Values ('Barranco Minas', '94343', 30);
Insert Into Municipality Values ('Mapiripana', '94663', 30);
Insert Into Municipality Values ('San Felipe', '94883', 30);
Insert Into Municipality Values ('Puerto Colombia', '94884', 30);
Insert Into Municipality Values ('La Guadalupe', '94885', 30);
Insert Into Municipality Values ('Cacahual', '94886', 30);
Insert Into Municipality Values ('Pana Pana', '94887', 30);
Insert Into Municipality Values ('Morichal', '94888', 30);
Insert Into Municipality Values ('Mitú', '97001', 32);
Insert Into Municipality Values ('Caruru', '97161', 32);
Insert Into Municipality Values ('Pacoa', '97511', 32);
Insert Into Municipality Values ('Taraira', '97666', 32);
Insert Into Municipality Values ('Papunaua', '97777', 32);
Insert Into Municipality Values ('Puerto Carreño', '99001', 33);
Insert Into Municipality Values ('La Primavera', '99524', 33);
Insert Into Municipality Values ('Santa Rosalía', '99624', 33);
Insert Into Municipality Values ('Cumaribo', '99773', 33);
Insert Into Municipality Values ('San José del Fragua', '18610', 7);
Insert Into Municipality Values ('Barranca de Upía', '50110', 16);
Insert Into Municipality Values ('Palmas del Socorro', '68524', 21);
Insert Into Municipality Values ('San Juan de Río Seco', '25662', 11);
Insert Into Municipality Values ('Juan de Acosta', '8372', 2);
Insert Into Municipality Values ('Fuente de Oro', '50287', 16);
Insert Into Municipality Values ('San Luis de Gaceno', '85325', 26);
Insert Into Municipality Values ('El Litoral del San Juan', '27250', 12);
Insert Into Municipality Values ('Villa de San Diego de Ubate', '25843', 11);
Insert Into Municipality Values ('Barranco de Loba', '13074', 4);
Insert Into Municipality Values ('Togüí', '15816', 5);
Insert Into Municipality Values ('Santa Rosa del Sur', '13688', 4);
Insert Into Municipality Values ('El Cantón del San Pablo', '27135', 12);
Insert Into Municipality Values ('Villa de Leyva', '15407', 5);
Insert Into Municipality Values ('San Sebastián de Buenavista', '47692', 15);
Insert Into Municipality Values ('Paz de Río', '15537', 5);
Insert Into Municipality Values ('Hatillo de Loba', '13300', 4);
Insert Into Municipality Values ('Sabanas de San Angel', '47660', 15);
Insert Into Municipality Values ('Calamar', '95015', 31);
Insert Into Municipality Values ('Río de Oro', '20614', 9);
Insert Into Municipality Values ('San Pedro de Uraba', '5665', 1);
Insert Into Municipality Values ('San José del Guaviare', '95001', 31);
Insert Into Municipality Values ('Santa Rosa de Viterbo', '15693', 5);
Insert Into Municipality Values ('Santander de Quilichao', '19698', 8);
Insert Into Municipality Values ('Miraflores', '95200', 31);
Insert Into Municipality Values ('Santafé de Antioquia', '5042', 1);
Insert Into Municipality Values ('San Carlos de Guaroa', '50680', 16);
Insert Into Municipality Values ('Palmar de Varela', '8520', 2);
Insert Into Municipality Values ('Santa Rosa de Osos', '5686', 1);
Insert Into Municipality Values ('San Andrés de Cuerquía', '5647', 1);
Insert Into Municipality Values ('Valle de San Juan', '73854', 23);
Insert Into Municipality Values ('San Vicente de Chucurí', '68689', 21);
Insert Into Municipality Values ('San José de Miranda', '68684', 21);
Insert Into Municipality Values ('Providencia', '88564', 28);
Insert Into Municipality Values ('Santa Rosa de Cabal', '66682', 20);
Insert Into Municipality Values ('Guayabal de Siquima', '25328', 11);
Insert Into Municipality Values ('Belén de Los Andaquies', '18094', 7);
Insert Into Municipality Values ('Paz de Ariporo', '85250', 26);
Insert Into Municipality Values ('Santa Helena del Opón', '68720', 21);
Insert Into Municipality Values ('San Pablo de Borbur', '15681', 5);
Insert Into Municipality Values ('La Jagua del Pilar', '44420', 14);
Insert Into Municipality Values ('La Jagua de Ibirico', '20400', 9);
Insert Into Municipality Values ('San Luis de Sincé', '70742', 22);
Insert Into Municipality Values ('San Luis de Gaceno', '15667', 5);
Insert Into Municipality Values ('El Carmen de Bolívar', '13244', 4);
Insert Into Municipality Values ('El Carmen de Atrato', '27245', 12);
Insert Into Municipality Values ('San Juan de Betulia', '70702', 22);
Insert Into Municipality Values ('Pijiño del Carmen', '47545', 15);
Insert Into Municipality Values ('Vigía del Fuerte', '5873', 1);
Insert Into Municipality Values ('San Martín de Loba', '13667', 4);
Insert Into Municipality Values ('Altos del Rosario', '13030', 4);
Insert Into Municipality Values ('Carmen de Apicala', '73148', 23);
Insert Into Municipality Values ('San Antonio del Tequendama', '25645', 11);
Insert Into Municipality Values ('Sabana de Torres', '68655', 21);
Insert Into Municipality Values ('El Retorno', '95025', 31);
Insert Into Municipality Values ('San José de Uré', '23682', 10);
Insert Into Municipality Values ('San Pedro de Cartago', '52694', 17);
Insert Into Municipality Values ('Campo de La Cruz', '8137', 2);
Insert Into Municipality Values ('San Juan de Arama', '50683', 16);
Insert Into Municipality Values ('San José de La Montaña', '5658', 1);
Insert Into Municipality Values ('Cartagena del Chairá', '18150', 7);
Insert Into Municipality Values ('San José del Palmar', '27660', 12);
Insert Into Municipality Values ('Agua de Dios', '25001', 11);
Insert Into Municipality Values ('San Jacinto del Cauca', '13655', 4);
Insert Into Municipality Values ('San Agustín', '41668', 13);
Insert Into Municipality Values ('El Tablón de Gómez', '52258', 17);
Insert Into Municipality Values ('San Andrés', '88001', 28);
Insert Into Municipality Values ('San José de Pare', '15664', 5);
Insert Into Municipality Values ('Valle de Guamez', '86865', 27);
Insert Into Municipality Values ('San Pablo de Borbur', '13670', 4);
Insert Into Municipality Values ('Santiago de Tolú', '70820', 22);
Insert Into Municipality Values ('Bogotá D.C.', '11001', 3);
Insert Into Municipality Values ('Carmen de Carupa', '25154', 11);
Insert Into Municipality Values ('Ciénaga de Oro', '23189', 10);
Insert Into Municipality Values ('San Juan de Urabá', '5659', 1);
Insert Into Municipality Values ('San Juan del Cesar', '44650', 14);
Insert Into Municipality Values ('El Carmen de Chucurí', '68235', 21);
Insert Into Municipality Values ('El Carmen de Viboral', '5148', 1);
Insert Into Municipality Values ('Belén de Umbría', '66088', 20);
Insert Into Municipality Values ('Belén de Bajira', '27086', 12);
Insert Into Municipality Values ('Valle de San José', '68855', 21);
Insert Into Municipality Values ('San Luis', '73678', 23);
Insert Into Municipality Values ('San Miguel de Sema', '15676', 5);
Insert Into Municipality Values ('San Antonio', '73675', 23);
Insert Into Municipality Values ('San Benito', '68673', 21);
Insert Into Municipality Values ('Vergara', '25862', 11);
Insert Into Municipality Values ('San Carlos', '23678', 10);
Insert Into Municipality Values ('Puerto Alegría', '91530', 29);
Insert Into Municipality Values ('Hato', '68344', 21);
Insert Into Municipality Values ('San Jacinto', '13654', 4);
Insert Into Municipality Values ('San Sebastián', '19693', 8);
Insert Into Municipality Values ('San Carlos', '5649', 1);
Insert Into Municipality Values ('Tuta', '15837', 5);
Insert Into Municipality Values ('Silos', '54743', 18);
Insert Into Municipality Values ('Cácota', '54125', 18);
Insert Into Municipality Values ('El Dovio', '76250', 24);
Insert Into Municipality Values ('Toledo', '54820', 18);
Insert Into Municipality Values ('Roldanillo', '76622', 24);
Insert Into Municipality Values ('Mutiscua', '54480', 18);
Insert Into Municipality Values ('Argelia', '76054', 24);
Insert Into Municipality Values ('El Zulia', '54261', 18);
Insert Into Municipality Values ('Salazar', '54660', 18);
Insert Into Municipality Values ('Sevilla', '76736', 24);
Insert Into Municipality Values ('Zarzal', '76895', 24);
Insert Into Municipality Values ('Cucutilla', '54223', 18);
Insert Into Municipality Values ('El Cerrito', '76248', 24);
Insert Into Municipality Values ('Cartago', '76147', 24);
Insert Into Municipality Values ('Caicedonia', '76122', 24);
Insert Into Municipality Values ('Puerto Santander', '54553', 18);
Insert Into Municipality Values ('Gramalote', '54313', 18);
Insert Into Municipality Values ('El Cairo', '76246', 24);
Insert Into Municipality Values ('El Tarra', '54250', 18);
Insert Into Municipality Values ('La Unión', '76400', 24);
Insert Into Municipality Values ('Restrepo', '76606', 24);
Insert Into Municipality Values ('Teorama', '54800', 18);
Insert Into Municipality Values ('Dagua', '76233', 24);
Insert Into Municipality Values ('Arboledas', '54051', 18);
Insert Into Municipality Values ('Guacarí', '76318', 24);
Insert Into Municipality Values ('Lourdes', '54418', 18);
Insert Into Municipality Values ('Ansermanuevo', '76041', 24);
Insert Into Municipality Values ('Bochalema', '54099', 18);
Insert Into Municipality Values ('Bugalagrande', '76113', 24);
Insert Into Municipality Values ('Convención', '54206', 18);
Insert Into Municipality Values ('Hacarí', '54344', 18);
Insert Into Municipality Values ('La Victoria', '76403', 24);
Insert Into Municipality Values ('Herrán', '54347', 18);
Insert Into Municipality Values ('Ginebra', '76306', 24);
Insert Into Municipality Values ('Yumbo', '76892', 24);
Insert Into Municipality Values ('Obando', '76497', 24);
Insert Into Municipality Values ('Tibú', '54810', 18);
Insert Into Municipality Values ('San Cayetano', '54673', 18);
Insert Into Municipality Values ('San Calixto', '54670', 18);
Insert Into Municipality Values ('Bolívar', '76100', 24);
Insert Into Municipality Values ('La Playa', '54398', 18);
Insert Into Municipality Values ('Cali', '76001', 24);
Insert Into Municipality Values ('San Pedro', '76670', 24);
Insert Into Municipality Values ('Guadalajara de Buga', '76111', 24);
Insert Into Municipality Values ('Chinácota', '54172', 18);
Insert Into Municipality Values ('Ragonvalia', '54599', 18);
Insert Into Municipality Values ('La Esperanza', '54385', 18);
Insert Into Municipality Values ('Villa del Rosario', '54874', 18);
Insert Into Municipality Values ('Chitagá', '54174', 18);
Insert Into Municipality Values ('Calima', '76126', 24);
Insert Into Municipality Values ('Sardinata', '54720', 18);
Insert Into Municipality Values ('Andalucía', '76036', 24);
Insert Into Municipality Values ('Pradera', '76563', 24);
Insert Into Municipality Values ('Abrego', '54003', 18);
Insert Into Municipality Values ('Los Patios', '54405', 18);
Insert Into Municipality Values ('Ocaña', '54498', 18);
Insert Into Municipality Values ('Bucarasica', '54109', 18);
Insert Into Municipality Values ('Yotoco', '76890', 24);
Insert Into Municipality Values ('Palmira', '76520', 24);
Insert Into Municipality Values ('Riofrío', '76616', 24);
Insert Into Municipality Values ('Santiago', '54680', 18);
Insert Into Municipality Values ('Alcalá', '76020', 24);
Insert Into Municipality Values ('Versalles', '76863', 24);
Insert Into Municipality Values ('Labateca', '54377', 18);
Insert Into Municipality Values ('Cachirá', '54128', 18);
Insert Into Municipality Values ('Villa Caro', '54871', 18);
Insert Into Municipality Values ('Durania', '54239', 18);
Insert Into Municipality Values ('El Águila', '76243', 24);
Insert Into Municipality Values ('Toro', '76823', 24);
Insert Into Municipality Values ('Candelaria', '76130', 24);
Insert Into Municipality Values ('La Cumbre', '76377', 24);
Insert Into Municipality Values ('Ulloa', '76845', 24);
Insert Into Municipality Values ('Trujillo', '76828', 24);
Insert Into Municipality Values ('Vijes', '76869', 24);
GO

Insert Into Eps Values ('COMPENSAR');
Insert Into Eps Values ('EPS SANITAS');
Insert Into Eps Values ('FAMISANAR EPS');
Insert Into Eps Values ('SALUD TOTAL EPS');
Insert Into Eps Values ('SURA EPS');
Insert Into Eps Values ('NUEVA EPS');
Insert Into Eps Values ('COOMEVA EPS');
Insert Into Eps Values ('CRUZ BLANCA EP');
Insert Into Eps Values ('EPS CONFENALCO VALLE');
Insert Into Eps Values ('EPS S.O.S');
Insert Into Eps Values ('ALIANSALUD EPS');
Insert Into Eps Values ('MEDIMÁS EPS');
GO

Insert Into Country(Code, [Name]) Values ('AF', 'AFGANISTÁN');
Insert Into Country(Code, [Name]) Values ('AL', 'ALBANIA');
Insert Into Country(Code, [Name]) Values ('DE', 'ALEMANIA');
Insert Into Country(Code, [Name]) Values ('AD', 'ANDORRA');
Insert Into Country(Code, [Name]) Values ('AO', 'ANGOLA');
Insert Into Country(Code, [Name]) Values ('AI', 'ANGUILLA');
Insert Into Country(Code, [Name]) Values ('AQ', 'ANTÁRTIDA');
Insert Into Country(Code, [Name]) Values ('AG', 'ANTIGUA Y BARBUDA');
Insert Into Country(Code, [Name]) Values ('AN', 'ANTILLAS HOLANDESAS');
Insert Into Country(Code, [Name]) Values ('SA', 'ARABIA SAUDÍ');
Insert Into Country(Code, [Name]) Values ('DZ', 'ARGELIA');
Insert Into Country(Code, [Name]) Values ('AR', 'ARGENTINA');
Insert Into Country(Code, [Name]) Values ('AM', 'ARMENIA');
Insert Into Country(Code, [Name]) Values ('AW', 'ARUBA');
Insert Into Country(Code, [Name]) Values ('MK', 'ARY MACEDONIA');
Insert Into Country(Code, [Name]) Values ('AU', 'AUSTRALIA');
Insert Into Country(Code, [Name]) Values ('AT', 'AUSTRIA');
Insert Into Country(Code, [Name]) Values ('AZ', 'AZERBAIYÁN');
Insert Into Country(Code, [Name]) Values ('BS', 'BAHAMAS');
Insert Into Country(Code, [Name]) Values ('BH', 'BAHRÉIN');
Insert Into Country(Code, [Name]) Values ('BD', 'BANGLADESH');
Insert Into Country(Code, [Name]) Values ('BB', 'BARBADOS');
Insert Into Country(Code, [Name]) Values ('BE', 'BÉLGICA');
Insert Into Country(Code, [Name]) Values ('BZ', 'BELICE');
Insert Into Country(Code, [Name]) Values ('BJ', 'BENIN');
Insert Into Country(Code, [Name]) Values ('BM', 'BERMUDAS');
Insert Into Country(Code, [Name]) Values ('BT', 'BHUTÁN');
Insert Into Country(Code, [Name]) Values ('BY', 'BIELORRUSIA');
Insert Into Country(Code, [Name]) Values ('BO', 'BOLIVIA');
Insert Into Country(Code, [Name]) Values ('BA', 'BOSNIA Y HERZEGOVINA');
Insert Into Country(Code, [Name]) Values ('BW', 'BOTSUANA');
Insert Into Country(Code, [Name]) Values ('BR', 'BRASIL');
Insert Into Country(Code, [Name]) Values ('BN', 'BRUNÉI');
Insert Into Country(Code, [Name]) Values ('BG', 'BULGARIA');
Insert Into Country(Code, [Name]) Values ('BF', 'BURKINA FASO');
Insert Into Country(Code, [Name]) Values ('BI', 'BURUNDI');
Insert Into Country(Code, [Name]) Values ('CV', 'CABO VERDE');
Insert Into Country(Code, [Name]) Values ('KH', 'CAMBOYA');
Insert Into Country(Code, [Name]) Values ('CM', 'CAMERÚN');
Insert Into Country(Code, [Name]) Values ('CA', 'CANADÁ');
Insert Into Country(Code, [Name]) Values ('TD', 'CHAD');
Insert Into Country(Code, [Name]) Values ('CL', 'CHILE');
Insert Into Country(Code, [Name]) Values ('CN', 'CHINA');
Insert Into Country(Code, [Name]) Values ('CY', 'CHIPRE');
Insert Into Country(Code, [Name]) Values ('VA', 'CIUDAD DEL VATICANO');
Insert Into Country(Code, [Name]) Values ('CO', 'COLOMBIA');
Insert Into Country(Code, [Name]) Values ('KM', 'COMORAS');
Insert Into Country(Code, [Name]) Values ('CG', 'CONGO');
Insert Into Country(Code, [Name]) Values ('KP', 'COREA DEL NORTE');
Insert Into Country(Code, [Name]) Values ('KR', 'COREA DEL SUR');
Insert Into Country(Code, [Name]) Values ('CI', 'COSTA DE MARFIL');
Insert Into Country(Code, [Name]) Values ('CR', 'COSTA RICA');
Insert Into Country(Code, [Name]) Values ('HR', 'CROACIA');
Insert Into Country(Code, [Name]) Values ('CU', 'CUBA');
Insert Into Country(Code, [Name]) Values ('DK', 'DINAMARCA');
Insert Into Country(Code, [Name]) Values ('DM', 'DOMINICA');
Insert Into Country(Code, [Name]) Values ('EC', 'ECUADOR');
Insert Into Country(Code, [Name]) Values ('EG', 'EGIPTO');
Insert Into Country(Code, [Name]) Values ('SV', 'EL SALVADOR');
Insert Into Country(Code, [Name]) Values ('AE', 'EMIRATOS ÁRABES UNIDOS');
Insert Into Country(Code, [Name]) Values ('ER', 'ERITREA');
Insert Into Country(Code, [Name]) Values ('SK', 'ESLOVAQUIA');
Insert Into Country(Code, [Name]) Values ('SI', 'ESLOVENIA');
Insert Into Country(Code, [Name]) Values ('ES', 'ESPAÑA');
Insert Into Country(Code, [Name]) Values ('US', 'ESTADOS UNIDOS');
Insert Into Country(Code, [Name]) Values ('EE', 'ESTONIA');
Insert Into Country(Code, [Name]) Values ('ET', 'ETIOPÍA');
Insert Into Country(Code, [Name]) Values ('PH', 'FILIPINAS');
Insert Into Country(Code, [Name]) Values ('FI', 'FINLANDIA');
Insert Into Country(Code, [Name]) Values ('FJ', 'FIYI');
Insert Into Country(Code, [Name]) Values ('FR', 'FRANCIA');
Insert Into Country(Code, [Name]) Values ('GA', 'GABÓN');
Insert Into Country(Code, [Name]) Values ('GM', 'GAMBIA');
Insert Into Country(Code, [Name]) Values ('GE', 'GEORGIA');
Insert Into Country(Code, [Name]) Values ('GH', 'GHANA');
Insert Into Country(Code, [Name]) Values ('GI', 'GIBRALTAR');
Insert Into Country(Code, [Name]) Values ('GD', 'GRANADA');
Insert Into Country(Code, [Name]) Values ('GR', 'GRECIA');
Insert Into Country(Code, [Name]) Values ('GL', 'GROENLANDIA');
Insert Into Country(Code, [Name]) Values ('GP', 'GUADALUPE');
Insert Into Country(Code, [Name]) Values ('GU', 'GUAM');
Insert Into Country(Code, [Name]) Values ('GT', 'GUATEMALA');
Insert Into Country(Code, [Name]) Values ('GF', 'GUAYANA FRANCESA');
Insert Into Country(Code, [Name]) Values ('GG', 'GUERNESEY');
Insert Into Country(Code, [Name]) Values ('GN', 'GUINEA');
Insert Into Country(Code, [Name]) Values ('GQ', 'GUINEA ECUATORIAL');
Insert Into Country(Code, [Name]) Values ('GW', 'GUINEA-BISSAU');
Insert Into Country(Code, [Name]) Values ('GY', 'GUYANA');
Insert Into Country(Code, [Name]) Values ('HT', 'HAITÍ');
Insert Into Country(Code, [Name]) Values ('NL', 'HOLANDA O PAÍSES BAJOS');
Insert Into Country(Code, [Name]) Values ('HN', 'HONDURAS');
Insert Into Country(Code, [Name]) Values ('HK', 'HONG KONG');
Insert Into Country(Code, [Name]) Values ('HU', 'HUNGRÍA');
Insert Into Country(Code, [Name]) Values ('IN', 'INDIA');
Insert Into Country(Code, [Name]) Values ('ID', 'INDONESIA');
Insert Into Country(Code, [Name]) Values ('IR', 'IRÁN');
Insert Into Country(Code, [Name]) Values ('IQ', 'IRAQ');
Insert Into Country(Code, [Name]) Values ('IE', 'IRLANDA');
Insert Into Country(Code, [Name]) Values ('BV', 'ISLA BOUVET');
Insert Into Country(Code, [Name]) Values ('IM', 'ISLA DE MAN');
Insert Into Country(Code, [Name]) Values ('CX', 'ISLA DE NAVIDAD');
Insert Into Country(Code, [Name]) Values ('NF', 'ISLA NORFOLK');
Insert Into Country(Code, [Name]) Values ('IS', 'ISLANDIA');
Insert Into Country(Code, [Name]) Values ('AX', 'ISLAS ALAND');
Insert Into Country(Code, [Name]) Values ('KY', 'ISLAS CAIMÁN');
Insert Into Country(Code, [Name]) Values ('CC', 'ISLAS COCOS');
Insert Into Country(Code, [Name]) Values ('CK', 'ISLAS COOK');
Insert Into Country(Code, [Name]) Values ('FO', 'ISLAS FEROE');
Insert Into Country(Code, [Name]) Values ('GS', 'ISLAS GEORGIAS DEL SUR Y SANDWICH DEL SUR');
Insert Into Country(Code, [Name]) Values ('HM', 'ISLAS HEARD Y MCDONALD');
Insert Into Country(Code, [Name]) Values ('FK', 'ISLAS MALVINAS');
Insert Into Country(Code, [Name]) Values ('MP', 'ISLAS MARIANAS DEL NORTE');
Insert Into Country(Code, [Name]) Values ('MH', 'ISLAS MARSHALL');
Insert Into Country(Code, [Name]) Values ('PN', 'ISLAS PITCAIRN');
Insert Into Country(Code, [Name]) Values ('SB', 'ISLAS SALOMÓN');
Insert Into Country(Code, [Name]) Values ('TC', 'ISLAS TURCAS Y CAICOS');
Insert Into Country(Code, [Name]) Values ('UM', 'ISLAS ULTRAMARINAS DE ESTADOS UNIDOS');
Insert Into Country(Code, [Name]) Values ('VG', 'ISLAS VÍRGENES BRITÁNICAS');
Insert Into Country(Code, [Name]) Values ('VI', 'ISLAS VÍRGENES DE LOS ESTADOS UNIDOS');
Insert Into Country(Code, [Name]) Values ('IL', 'ISRAEL');
Insert Into Country(Code, [Name]) Values ('IT', 'ITALIA');
Insert Into Country(Code, [Name]) Values ('JM', 'JAMAICA');
Insert Into Country(Code, [Name]) Values ('JP', 'JAPÓN');
Insert Into Country(Code, [Name]) Values ('JE', 'JERSEY');
Insert Into Country(Code, [Name]) Values ('JO', 'JORDANIA');
Insert Into Country(Code, [Name]) Values ('KZ', 'KAZAJSTÁN');
Insert Into Country(Code, [Name]) Values ('KE', 'KENIA');
Insert Into Country(Code, [Name]) Values ('KG', 'KIRGUISTÁN');
Insert Into Country(Code, [Name]) Values ('KI', 'KIRIBATI');
Insert Into Country(Code, [Name]) Values ('KW', 'KUWAIT');
Insert Into Country(Code, [Name]) Values ('LA', 'LAOS');
Insert Into Country(Code, [Name]) Values ('LS', 'LESOTHO');
Insert Into Country(Code, [Name]) Values ('LV', 'LETONIA');
Insert Into Country(Code, [Name]) Values ('LB', 'LÍBANO');
Insert Into Country(Code, [Name]) Values ('LR', 'LIBERIA');
Insert Into Country(Code, [Name]) Values ('LY', 'LIBIA');
Insert Into Country(Code, [Name]) Values ('LI', 'LIECHTENSTEIN');
Insert Into Country(Code, [Name]) Values ('LT', 'LITUANIA');
Insert Into Country(Code, [Name]) Values ('LU', 'LUXEMBURGO');
Insert Into Country(Code, [Name]) Values ('MO', 'MACAO');
Insert Into Country(Code, [Name]) Values ('MG', 'MADAGASCAR');
Insert Into Country(Code, [Name]) Values ('MY', 'MALASIA');
Insert Into Country(Code, [Name]) Values ('MW', 'MALAWI');
Insert Into Country(Code, [Name]) Values ('MV', 'MALDIVAS');
Insert Into Country(Code, [Name]) Values ('ML', 'MALÍ');
Insert Into Country(Code, [Name]) Values ('MT', 'MALTA');
Insert Into Country(Code, [Name]) Values ('MA', 'MARRUECOS');
Insert Into Country(Code, [Name]) Values ('MQ', 'MARTINICA');
Insert Into Country(Code, [Name]) Values ('MU', 'MAURICIO');
Insert Into Country(Code, [Name]) Values ('MR', 'MAURITANIA');
Insert Into Country(Code, [Name]) Values ('YT', 'MAYOTTE');
Insert Into Country(Code, [Name]) Values ('MX', 'MÉXICO');
Insert Into Country(Code, [Name]) Values ('FM', 'MICRONESIA');
Insert Into Country(Code, [Name]) Values ('MD', 'MOLDAVIA');
Insert Into Country(Code, [Name]) Values ('MC', 'MÓNACO');
Insert Into Country(Code, [Name]) Values ('MN', 'MONGOLIA');
Insert Into Country(Code, [Name]) Values ('MS', 'MONTSERRAT');
Insert Into Country(Code, [Name]) Values ('MZ', 'MOZAMBIQUE');
Insert Into Country(Code, [Name]) Values ('MM', 'MYANMAR');
Insert Into Country(Code, [Name]) Values ('NA', 'NAMIBIA');
Insert Into Country(Code, [Name]) Values ('NR', 'NAURU');
Insert Into Country(Code, [Name]) Values ('NP', 'NEPAL');
Insert Into Country(Code, [Name]) Values ('NI', 'NICARAGUA');
Insert Into Country(Code, [Name]) Values ('NE', 'NÍGER');
Insert Into Country(Code, [Name]) Values ('NG', 'NIGERIA');
Insert Into Country(Code, [Name]) Values ('NU', 'NIUE');
Insert Into Country(Code, [Name]) Values ('NO', 'NORUEGA');
Insert Into Country(Code, [Name]) Values ('NC', 'NUEVA CALEDONIA');
Insert Into Country(Code, [Name]) Values ('NZ', 'NUEVA ZELANDA');
Insert Into Country(Code, [Name]) Values ('OM', 'OMÁN');
Insert Into Country(Code, [Name]) Values ('PK', 'PAKISTÁN');
Insert Into Country(Code, [Name]) Values ('PW', 'PALAU');
Insert Into Country(Code, [Name]) Values ('PS', 'PALESTINA');
Insert Into Country(Code, [Name]) Values ('PA', 'PANAMÁ');
Insert Into Country(Code, [Name]) Values ('PG', 'PAPÚA NUEVA GUINEA');
Insert Into Country(Code, [Name]) Values ('PY', 'PARAGUAY');
Insert Into Country(Code, [Name]) Values ('PE', 'PERÚ');
Insert Into Country(Code, [Name]) Values ('PF', 'POLINESIA FRANCESA');
Insert Into Country(Code, [Name]) Values ('PL', 'POLONIA');
Insert Into Country(Code, [Name]) Values ('PT', 'PORTUGAL');
Insert Into Country(Code, [Name]) Values ('PR', 'PUERTO RICO');
Insert Into Country(Code, [Name]) Values ('QA', 'QATAR');
Insert Into Country(Code, [Name]) Values ('GB', 'REINO UNIDO');
Insert Into Country(Code, [Name]) Values ('CF', 'REPÚBLICA CENTROAFRICANA');
Insert Into Country(Code, [Name]) Values ('CZ', 'REPÚBLICA CHECA');
Insert Into Country(Code, [Name]) Values ('CD', 'REPÚBLICA DEMOCRÁTICA DEL CONGO');
Insert Into Country(Code, [Name]) Values ('DO', 'REPÚBLICA DOMINICANA');
Insert Into Country(Code, [Name]) Values ('RE', 'REUNIÓN');
Insert Into Country(Code, [Name]) Values ('RW', 'RUANDA');
Insert Into Country(Code, [Name]) Values ('RO', 'RUMANIA');
Insert Into Country(Code, [Name]) Values ('RU', 'RUSIA');
Insert Into Country(Code, [Name]) Values ('EH', 'SAHARA OCCIDENTAL');
Insert Into Country(Code, [Name]) Values ('WS', 'SAMOA');
Insert Into Country(Code, [Name]) Values ('AS', 'SAMOA AMERICANA');
Insert Into Country(Code, [Name]) Values ('KN', 'SAN CRISTÓBAL Y NEVIS');
Insert Into Country(Code, [Name]) Values ('SM', 'SAN MARINO');
Insert Into Country(Code, [Name]) Values ('PM', 'SAN PEDRO Y MIQUELÓN');
Insert Into Country(Code, [Name]) Values ('VC', 'SAN VICENTE Y LAS GRANADINAS');
Insert Into Country(Code, [Name]) Values ('SH', 'SANTA HELENA');
Insert Into Country(Code, [Name]) Values ('LC', 'SANTA LUCÍA');
Insert Into Country(Code, [Name]) Values ('ST', 'SANTO TOMÉ Y PRÍNCIPE');
Insert Into Country(Code, [Name]) Values ('SN', 'SENEGAL');
Insert Into Country(Code, [Name]) Values ('CS', 'SERBIA Y MONTENEGRO');
Insert Into Country(Code, [Name]) Values ('SC', 'SEYCHELLES');
Insert Into Country(Code, [Name]) Values ('SL', 'SIERRA LEONA');
Insert Into Country(Code, [Name]) Values ('SG', 'SINGAPUR');
Insert Into Country(Code, [Name]) Values ('SY', 'SIRIA');
Insert Into Country(Code, [Name]) Values ('SO', 'SOMALIA');
Insert Into Country(Code, [Name]) Values ('LK', 'SRI LANKA');
Insert Into Country(Code, [Name]) Values ('SZ', 'SUAZILANDIA');
Insert Into Country(Code, [Name]) Values ('ZA', 'SUDÁFRICA');
Insert Into Country(Code, [Name]) Values ('SD', 'SUDÁN');
Insert Into Country(Code, [Name]) Values ('SE', 'SUECIA');
Insert Into Country(Code, [Name]) Values ('CH', 'SUIZA');
Insert Into Country(Code, [Name]) Values ('SR', 'SURINAM');
Insert Into Country(Code, [Name]) Values ('SJ', 'SVALBARD Y JAN MAYEN');
Insert Into Country(Code, [Name]) Values ('TH', 'TAILANDIA');
Insert Into Country(Code, [Name]) Values ('TW', 'TAIWÁN');
Insert Into Country(Code, [Name]) Values ('TZ', 'TANZANIA');
Insert Into Country(Code, [Name]) Values ('TJ', 'TAYIKISTÁN');
Insert Into Country(Code, [Name]) Values ('IO', 'TERRITORIO BRITÁNICO DEL OCÉANO ÍNDICO');
Insert Into Country(Code, [Name]) Values ('TF', 'TERRITORIOS AUSTRALES FRANCESES');
Insert Into Country(Code, [Name]) Values ('TL', 'TIMOR ORIENTAL');
Insert Into Country(Code, [Name]) Values ('TG', 'TOGO');
Insert Into Country(Code, [Name]) Values ('TK', 'TOKELAU');
Insert Into Country(Code, [Name]) Values ('TO', 'TONGA');
Insert Into Country(Code, [Name]) Values ('TT', 'TRINIDAD Y TOBAGO');
Insert Into Country(Code, [Name]) Values ('TN', 'TÚNEZ');
Insert Into Country(Code, [Name]) Values ('TM', 'TURKMENISTÁN');
Insert Into Country(Code, [Name]) Values ('TR', 'TURQUÍA');
Insert Into Country(Code, [Name]) Values ('TV', 'TUVALU');
Insert Into Country(Code, [Name]) Values ('UA', 'UCRANIA');
Insert Into Country(Code, [Name]) Values ('UG', 'UGANDA');
Insert Into Country(Code, [Name]) Values ('UY', 'URUGUAY');
Insert Into Country(Code, [Name]) Values ('UZ', 'UZBEKISTÁN');
Insert Into Country(Code, [Name]) Values ('VU', 'VANUATU');
Insert Into Country(Code, [Name]) Values ('VE', 'VENEZUELA');
Insert Into Country(Code, [Name]) Values ('VN', 'VIETNAM');
Insert Into Country(Code, [Name]) Values ('WF', 'WALLIS Y FUTUNA');
Insert Into Country(Code, [Name]) Values ('YE', 'YEMEN');
Insert Into Country(Code, [Name]) Values ('DJ', 'YIBUTI');
Insert Into Country(Code, [Name]) Values ('ZM', 'ZAMBIA');
Insert Into Country(Code, [Name]) Values ('ZW', 'ZIMBAWE');
GO

Insert Into IdentificationType(Code, [Name]) Values ('CC', 'Cédula');
Insert Into IdentificationType(Code, [Name]) Values ('CE', 'Cédula de extranjería');
Insert Into IdentificationType(Code, [Name]) Values ('PAS', 'Pasaporte');
GO

INSERT INTO dbo.BloodType VALUES ('O-')
INSERT INTO dbo.BloodType VALUES ('O+')
INSERT INTO dbo.BloodType VALUES ('A-')
INSERT INTO dbo.BloodType VALUES ('A+')
INSERT INTO dbo.BloodType VALUES ('B-')
INSERT INTO dbo.BloodType VALUES ('B+')
INSERT INTO dbo.BloodType VALUES ('AB-')
INSERT INTO dbo.BloodType VALUES ('AB+')
GO

INSERT INTO ContractType VALUES ('PLANTA')
INSERT INTO ContractType VALUES ('OPS')
GO

INSERT INTO Gender VALUES ('M')
INSERT INTO Gender VALUES ('F')
GO

