BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CheckListResponseDetail
	DROP CONSTRAINT FK_CheckListResponseDetail_CheckListQuestion_QuestionId
GO
ALTER TABLE dbo.CheckListQuestion SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.CheckListResponseDetail SET (LOCK_ESCALATION = TABLE)
GO
COMMIT