// <auto-generated />
using System;
using IVSoftware.Web.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IVSoftware.Web.Migrations
{
    [DbContext(typeof(IVSoftwareContext))]
    [Migration("20201207180915_EquipmentChecklistEntitiesAdded")]
    partial class EquipmentChecklistEntitiesAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("CheckListQuestionCheckListSection", b =>
                {
                    b.Property<int>("QuestionsId")
                        .HasColumnType("int");

                    b.Property<int>("SectionsId")
                        .HasColumnType("int");

                    b.HasKey("QuestionsId", "SectionsId");

                    b.HasIndex("SectionsId");

                    b.ToTable("CheckListQuestionCheckListSection");
                });

            modelBuilder.Entity("CheckListQuestionEquipmentCheckList", b =>
                {
                    b.Property<int>("CheckListId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionsId")
                        .HasColumnType("int");

                    b.HasKey("CheckListId", "QuestionsId");

                    b.HasIndex("QuestionsId");

                    b.ToTable("CheckListQuestionEquipmentCheckList");
                });

            modelBuilder.Entity("CheckListSectionEquipmentCheckList", b =>
                {
                    b.Property<int>("CheckListsId")
                        .HasColumnType("int");

                    b.Property<int>("SectionsId")
                        .HasColumnType("int");

                    b.HasKey("CheckListsId", "SectionsId");

                    b.HasIndex("SectionsId");

                    b.ToTable("CheckListSectionEquipmentCheckList");
                });

            modelBuilder.Entity("EquipmentEquipmentCheckList", b =>
                {
                    b.Property<int>("CheckListsId")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentsId")
                        .HasColumnType("int");

                    b.HasKey("CheckListsId", "EquipmentsId");

                    b.HasIndex("EquipmentsId");

                    b.ToTable("EquipmentEquipmentCheckList");
                });

            modelBuilder.Entity("IVSoftware.Models.ClientModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClientTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRegular")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastServiceExecutionDatetime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModificationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegisterStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientTypeId");

                    b.HasIndex("DocumentTypeId");

                    b.ToTable("ClientModel");
                });

            modelBuilder.Entity("IVSoftware.Models.ClientTypeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModificationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MustPayServices")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegisterStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ClientTypeModel");
                });

            modelBuilder.Entity("IVSoftware.Models.MatrixModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OnlyForServices")
                        .HasColumnType("bit");

                    b.Property<int>("RegisterStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MatrixModel");
                });

            modelBuilder.Entity("IVSoftware.Models.MeasurementUnitModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModificationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegisterStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MeasurementUnitModel");
                });

            modelBuilder.Entity("IVSoftware.Models.QuotationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClientAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientContactPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Exceptions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Greetings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("MeasurementSubtotal")
                        .HasColumnType("real");

                    b.Property<float>("MeasurementTotalValue")
                        .HasColumnType("real");

                    b.Property<DateTime?>("ModificationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegisterStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReservationMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ServicesSubtotal")
                        .HasColumnType("real");

                    b.Property<float>("ServicesTotalValue")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("QuotationModel");
                });

            modelBuilder.Entity("IVSoftware.Models.QuotationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("ClientRequestDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("GenerationUsedId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("HasBeenGenerated")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastGenerationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModificationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegisterStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("GenerationUsedId");

                    b.HasIndex("StatusId");

                    b.ToTable("QuotationRequest");
                });

            modelBuilder.Entity("IVSoftware.Models.ReferenceMethodCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuotationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegisterStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ReferenceMethodCondition");
                });

            modelBuilder.Entity("IVSoftware.Models.ReferenceMethodModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasUncertainty")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPercentage")
                        .HasColumnType("bit");

                    b.Property<float>("MeasurementUncertaintyLowerValue")
                        .HasColumnType("real");

                    b.Property<float>("MeasurementUncertaintyUpperValue")
                        .HasColumnType("real");

                    b.Property<DateTime?>("ModificationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegisterStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ReferenceMethodModel");
                });

            modelBuilder.Entity("IVSoftware.Models.ServiceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MatrixGroupId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReferenceMethodId")
                        .HasColumnType("int");

                    b.Property<int>("RegisterStatus")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceGroupModelId")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceTypeId")
                        .HasColumnType("int");

                    b.Property<float>("UnitValue")
                        .HasColumnType("real");

                    b.Property<int?>("VariableId")
                        .HasColumnType("int");

                    b.Property<int?>("WorkingRangeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatrixGroupId");

                    b.HasIndex("ReferenceMethodId");

                    b.HasIndex("ServiceGroupModelId");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("VariableId");

                    b.HasIndex("WorkingRangeId");

                    b.ToTable("ServiceModel");
                });

            modelBuilder.Entity("IVSoftware.Models.VariableModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MeasurementUnitId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegisterStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementUnitId");

                    b.ToTable("VariableModel");
                });

            modelBuilder.Entity("IVSoftware.Models.WorkingRangeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("MaximumValue")
                        .HasColumnType("real");

                    b.Property<float>("MinimumValue")
                        .HasColumnType("real");

                    b.Property<DateTime?>("ModificationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Precondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegisterStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WorkingRangeModel");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.AplicacionEvaluacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("EvaluacionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAplicacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("PersonaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EvaluacionId");

                    b.HasIndex("PersonaId");

                    b.ToTable("AplicacionEvaluacion");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.Arl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Arl");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModificationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegisterStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Brand");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.CheckListQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModificationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegisterStatus")
                        .HasColumnType("int");

                    b.Property<int>("TypeOfQuestion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CheckListQuestion");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.CheckListSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModificationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegisterStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CheckListSection");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.ConocimientoTecnico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("Analisis")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Matriz")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PersonaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TecnicaAnalitica")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Tiempo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.ToTable("ConocimientoTecnico");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.DetalleEvaluacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AplicacionEvaluacionId")
                        .HasColumnType("int");

                    b.Property<int>("PreguntaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AplicacionEvaluacionId");

                    b.HasIndex("PreguntaId");

                    b.ToTable("DetalleEvaluacion");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.EducacionBasica", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<DateTime>("FechaGrado")
                        .HasColumnType("datetime");

                    b.Property<string>("NombreInstitucion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PersonaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TituloObtenido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UltimoGradoAprobado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.ToTable("EducacionBasica");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.EducacionSuperior", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("ArchivoAdjunto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsGraduado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaGrado")
                        .HasColumnType("datetime");

                    b.Property<int>("ModalidadAcademicaId")
                        .HasColumnType("int");

                    b.Property<string>("NombreEstudios")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NombreInstitucion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NumeroTarjetaProfesional")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("PersonaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SemestresAprobados")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModalidadAcademicaId");

                    b.HasIndex("PersonaId");

                    b.ToTable("EducacionSuperior");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.Eps", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Eps");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<float>("Accuracy")
                        .HasColumnType("real");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EquipBrandId")
                        .HasColumnType("int");

                    b.Property<int?>("EquipProviderId")
                        .HasColumnType("int");

                    b.Property<string>("Magnitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("MinimumRead")
                        .HasColumnType("real");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherRecomendation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PowerSupply")
                        .HasColumnType("real");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Range")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegisterStatus")
                        .HasColumnType("int");

                    b.Property<string>("Serie")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EquipBrandId");

                    b.HasIndex("EquipProviderId");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.EquipmentCheckList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModificationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegisterStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EquipmentCheckList");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.Evaluacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Evaluacion");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.ExperienciaLaboral", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("ArchivoAdjunto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CargoContrato")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CorreoElectronico")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Dependencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("EsActual")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaRetiro")
                        .HasColumnType("datetime");

                    b.Property<int?>("MunicipioId")
                        .HasColumnType("int");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("PaisId")
                        .HasColumnType("int");

                    b.Property<string>("PersonaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Responsabilidades")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("TipoEmpresaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MunicipioId");

                    b.HasIndex("PaisId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("TipoEmpresaId");

                    b.ToTable("ExperienciaLaboral");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.Formacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("ArchivoAdjunto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("FechaFinalizacion")
                        .HasColumnType("datetime");

                    b.Property<string>("NombreCurso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("NumeroHoras")
                        .HasColumnType("int");

                    b.Property<string>("PersonaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Tema")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TipoCertificacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.HasIndex("TipoCertificacionId");

                    b.ToTable("Formacion");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.Idioma", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<int>("Escribe")
                        .HasColumnType("int");

                    b.Property<int>("Habla")
                        .HasColumnType("int");

                    b.Property<int>("Lee")
                        .HasColumnType("int");

                    b.Property<string>("PersonaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("TipoIdiomaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.HasIndex("TipoIdiomaId");

                    b.ToTable("Idioma");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.ModalidadAcademica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ModalidadAcademica");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.Municipio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<int?>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Municipio");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.OtroConocimiento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PersonaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Tiempo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.ToTable("OtroConocimiento");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Pais");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.Persona", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("ArlId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DistritoMilitar")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("EpsId")
                        .HasColumnType("int");

                    b.Property<bool?>("EsColombiano")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaDiligenciamiento")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime");

                    b.Property<string>("Foto")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Habilidades")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("MunicipioCorrespondenciaId")
                        .HasColumnType("int");

                    b.Property<int?>("MunicipioNacimientoId")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NumeroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NumeroLibretaMilitar")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("PaisCorrespondenciaId")
                        .HasColumnType("int");

                    b.Property<int?>("PaisNacimientoId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoApellido")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("SegundoNombre")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Sexo")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("TipoContratoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("int");

                    b.Property<string>("TipoLibretaMilitar")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<int?>("TipoSangreId")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ArlId");

                    b.HasIndex("EpsId");

                    b.HasIndex("MunicipioCorrespondenciaId");

                    b.HasIndex("MunicipioNacimientoId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("PaisCorrespondenciaId");

                    b.HasIndex("PaisNacimientoId");

                    b.HasIndex("TipoContratoId");

                    b.HasIndex("TipoDocumentoId");

                    b.HasIndex("TipoSangreId");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.PersonaInduccion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<DateTime>("FechaInduccion")
                        .HasColumnType("datetime2");

                    b.Property<string>("PersonaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TipoInduccionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.HasIndex("TipoInduccionId");

                    b.ToTable("PersonaInduccion");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.Pregunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Enunciado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EvaluacionId")
                        .HasColumnType("int");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int>("TipoPregunta")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EvaluacionId");

                    b.ToTable("Pregunta");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegisterStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Provider");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.QuotationStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModificationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegisterStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("QuotationStatus");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.Respuesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int>("PreguntaId")
                        .HasColumnType("int");

                    b.Property<bool>("RespuestaCorrecta")
                        .HasColumnType("bit");

                    b.Property<string>("Texto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PreguntaId");

                    b.ToTable("Respuesta");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.RespuestaEvaluacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("DetalleEvaluacionId")
                        .HasColumnType("int");

                    b.Property<int>("PreguntaId")
                        .HasColumnType("int");

                    b.Property<int?>("RespuestaId")
                        .HasColumnType("int");

                    b.Property<string>("TextoRespuesta")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DetalleEvaluacionId");

                    b.HasIndex("PreguntaId");

                    b.HasIndex("RespuestaId");

                    b.ToTable("RespuestaEvaluacion");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.RolSistemaGestion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<int>("IndicadorAutorizacion")
                        .HasColumnType("int");

                    b.Property<string>("PersonaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("TipoRolGestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.HasIndex("TipoRolGestionId");

                    b.ToTable("RolSistemaGestion");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.ServiceGroupModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegisterStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ServiceGroupModel");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.TipoCertificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoCertificacion");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.TipoContrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoContrato");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.TipoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("TipoDocumento");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.TipoEmpresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoEmpresa");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.TipoIdioma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("TipoIdioma");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.TipoInduccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoInduccion");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.TipoRolGestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("TipoRolGestion");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.TipoSangre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.HasKey("Id");

                    b.ToTable("TipoSangre");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.TypeOfService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificationDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegisterStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TypeOfService");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("CheckListQuestionCheckListSection", b =>
                {
                    b.HasOne("IVSoftware.Web.Models.CheckListQuestion", null)
                        .WithMany()
                        .HasForeignKey("QuestionsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IVSoftware.Web.Models.CheckListSection", null)
                        .WithMany()
                        .HasForeignKey("SectionsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CheckListQuestionEquipmentCheckList", b =>
                {
                    b.HasOne("IVSoftware.Web.Models.EquipmentCheckList", null)
                        .WithMany()
                        .HasForeignKey("CheckListId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IVSoftware.Web.Models.CheckListQuestion", null)
                        .WithMany()
                        .HasForeignKey("QuestionsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CheckListSectionEquipmentCheckList", b =>
                {
                    b.HasOne("IVSoftware.Web.Models.EquipmentCheckList", null)
                        .WithMany()
                        .HasForeignKey("CheckListsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IVSoftware.Web.Models.CheckListSection", null)
                        .WithMany()
                        .HasForeignKey("SectionsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EquipmentEquipmentCheckList", b =>
                {
                    b.HasOne("IVSoftware.Web.Models.EquipmentCheckList", null)
                        .WithMany()
                        .HasForeignKey("CheckListsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IVSoftware.Web.Models.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("IVSoftware.Models.ClientModel", b =>
                {
                    b.HasOne("IVSoftware.Models.ClientTypeModel", "ClientType")
                        .WithMany()
                        .HasForeignKey("ClientTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IVSoftware.Web.Models.TipoDocumento", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ClientType");

                    b.Navigation("DocumentType");
                });

            modelBuilder.Entity("IVSoftware.Models.QuotationRequest", b =>
                {
                    b.HasOne("IVSoftware.Models.ClientModel", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IVSoftware.Web.Models.Persona", "GenerationUsed")
                        .WithMany()
                        .HasForeignKey("GenerationUsedId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IVSoftware.Web.Models.QuotationStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Client");

                    b.Navigation("GenerationUsed");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("IVSoftware.Models.ServiceModel", b =>
                {
                    b.HasOne("IVSoftware.Models.MatrixModel", "MatrixGroup")
                        .WithMany()
                        .HasForeignKey("MatrixGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IVSoftware.Models.ReferenceMethodModel", "ReferenceMethod")
                        .WithMany()
                        .HasForeignKey("ReferenceMethodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IVSoftware.Web.Models.ServiceGroupModel", null)
                        .WithMany("Services")
                        .HasForeignKey("ServiceGroupModelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IVSoftware.Web.Models.TypeOfService", "ServiceType")
                        .WithMany()
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IVSoftware.Models.VariableModel", "Variable")
                        .WithMany()
                        .HasForeignKey("VariableId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IVSoftware.Models.WorkingRangeModel", "WorkingRange")
                        .WithMany()
                        .HasForeignKey("WorkingRangeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MatrixGroup");

                    b.Navigation("ReferenceMethod");

                    b.Navigation("ServiceType");

                    b.Navigation("Variable");

                    b.Navigation("WorkingRange");
                });

            modelBuilder.Entity("IVSoftware.Models.VariableModel", b =>
                {
                    b.HasOne("IVSoftware.Models.MeasurementUnitModel", "MeasurementUnit")
                        .WithMany()
                        .HasForeignKey("MeasurementUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MeasurementUnit");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.AplicacionEvaluacion", b =>
                {
                    b.HasOne("IVSoftware.Web.Models.Evaluacion", "Evaluacion")
                        .WithMany()
                        .HasForeignKey("EvaluacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IVSoftware.Web.Models.Persona", "Persona")
                        .WithMany("ListAplicacionEvaluacion")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evaluacion");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.ConocimientoTecnico", b =>
                {
                    b.HasOne("IVSoftware.Web.Models.Persona", "Persona")
                        .WithMany("ListConocimientoTecnico")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.DetalleEvaluacion", b =>
                {
                    b.HasOne("IVSoftware.Web.Models.AplicacionEvaluacion", "AplicacionEvaluacion")
                        .WithMany()
                        .HasForeignKey("AplicacionEvaluacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IVSoftware.Web.Models.Respuesta", "Pregunta")
                        .WithMany()
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AplicacionEvaluacion");

                    b.Navigation("Pregunta");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.EducacionBasica", b =>
                {
                    b.HasOne("IVSoftware.Web.Models.Persona", "Persona")
                        .WithMany("ListEducacionBasica")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.EducacionSuperior", b =>
                {
                    b.HasOne("IVSoftware.Web.Models.ModalidadAcademica", "ModalidadAcademica")
                        .WithMany("ListEducacionSuperior")
                        .HasForeignKey("ModalidadAcademicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IVSoftware.Web.Models.Persona", "Persona")
                        .WithMany("ListEducacionSuperior")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ModalidadAcademica");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.Equipment", b =>
                {
                    b.HasOne("IVSoftware.Web.Models.Brand", "EquipBrand")
                        .WithMany()
                        .HasForeignKey("EquipBrandId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IVSoftware.Web.Models.Provider", "EquipProvider")
                        .WithMany()
                        .HasForeignKey("EquipProviderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EquipBrand");

                    b.Navigation("EquipProvider");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.ExperienciaLaboral", b =>
                {
                    b.HasOne("IVSoftware.Web.Models.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IVSoftware.Web.Models.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IVSoftware.Web.Models.Persona", "Persona")
                        .WithMany("ListExperienciaLaboral")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IVSoftware.Web.Models.TipoEmpresa", "TipoEmpresa")
                        .WithMany("ListExperienciaLaboral")
                        .HasForeignKey("TipoEmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Municipio");

                    b.Navigation("Pais");

                    b.Navigation("Persona");

                    b.Navigation("TipoEmpresa");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.Formacion", b =>
                {
                    b.HasOne("IVSoftware.Web.Models.Persona", "Persona")
                        .WithMany("ListFormacion")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IVSoftware.Web.Models.TipoCertificacion", "TipoCertificacion")
                        .WithMany("ListFormacion")
                        .HasForeignKey("TipoCertificacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");

                    b.Navigation("TipoCertificacion");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.Idioma", b =>
                {
                    b.HasOne("IVSoftware.Web.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IVSoftware.Web.Models.TipoIdioma", "TipoIdioma")
                        .WithMany()
                        .HasForeignKey("TipoIdiomaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Persona");

                    b.Navigation("TipoIdioma");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.Municipio", b =>
                {
                    b.HasOne("IVSoftware.Web.Models.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.OtroConocimiento", b =>
                {
                    b.HasOne("IVSoftware.Web.Models.Persona", "Persona")
                        .WithMany("ListOtroConocimiento")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.Persona", b =>
                {
                    b.HasOne("IVSoftware.Web.Models.Arl", "Arl")
                        .WithMany()
                        .HasForeignKey("ArlId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IVSoftware.Web.Models.Eps", "Eps")
                        .WithMany()
                        .HasForeignKey("EpsId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IVSoftware.Web.Models.Municipio", "MunicipioCorrespondencia")
                        .WithMany()
                        .HasForeignKey("MunicipioCorrespondenciaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IVSoftware.Web.Models.Municipio", "MunicipioNacimiento")
                        .WithMany()
                        .HasForeignKey("MunicipioNacimientoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IVSoftware.Web.Models.Pais", "PaisCorrespondencia")
                        .WithMany()
                        .HasForeignKey("PaisCorrespondenciaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IVSoftware.Web.Models.Pais", "PaisNacimiento")
                        .WithMany()
                        .HasForeignKey("PaisNacimientoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IVSoftware.Web.Models.TipoContrato", "TipoContrato")
                        .WithMany()
                        .HasForeignKey("TipoContratoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IVSoftware.Web.Models.TipoDocumento", "TipoDocumento")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IVSoftware.Web.Models.TipoSangre", "TipoSangre")
                        .WithMany()
                        .HasForeignKey("TipoSangreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Arl");

                    b.Navigation("Eps");

                    b.Navigation("MunicipioCorrespondencia");

                    b.Navigation("MunicipioNacimiento");

                    b.Navigation("PaisCorrespondencia");

                    b.Navigation("PaisNacimiento");

                    b.Navigation("TipoContrato");

                    b.Navigation("TipoDocumento");

                    b.Navigation("TipoSangre");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.PersonaInduccion", b =>
                {
                    b.HasOne("IVSoftware.Web.Models.Persona", "Persona")
                        .WithMany("ListPersonaInduccion")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IVSoftware.Web.Models.TipoInduccion", "TipoInduccion")
                        .WithMany()
                        .HasForeignKey("TipoInduccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");

                    b.Navigation("TipoInduccion");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.Pregunta", b =>
                {
                    b.HasOne("IVSoftware.Web.Models.Evaluacion", "Evaluacion")
                        .WithMany("ListPregunta")
                        .HasForeignKey("EvaluacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evaluacion");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.Respuesta", b =>
                {
                    b.HasOne("IVSoftware.Web.Models.Pregunta", "Pregunta")
                        .WithMany("ListRespuesta")
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pregunta");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.RespuestaEvaluacion", b =>
                {
                    b.HasOne("IVSoftware.Web.Models.DetalleEvaluacion", "DetalleEvaluacion")
                        .WithMany()
                        .HasForeignKey("DetalleEvaluacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IVSoftware.Web.Models.Pregunta", "Pregunta")
                        .WithMany()
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IVSoftware.Web.Models.Respuesta", "Respuesta")
                        .WithMany()
                        .HasForeignKey("RespuestaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DetalleEvaluacion");

                    b.Navigation("Pregunta");

                    b.Navigation("Respuesta");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.RolSistemaGestion", b =>
                {
                    b.HasOne("IVSoftware.Web.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IVSoftware.Web.Models.TipoRolGestion", "TipoRolGestion")
                        .WithMany()
                        .HasForeignKey("TipoRolGestionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Persona");

                    b.Navigation("TipoRolGestion");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("IVSoftware.Web.Models.Persona", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("IVSoftware.Web.Models.Persona", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IVSoftware.Web.Models.Persona", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("IVSoftware.Web.Models.Persona", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IVSoftware.Web.Models.Evaluacion", b =>
                {
                    b.Navigation("ListPregunta");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.ModalidadAcademica", b =>
                {
                    b.Navigation("ListEducacionSuperior");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.Persona", b =>
                {
                    b.Navigation("ListAplicacionEvaluacion");

                    b.Navigation("ListConocimientoTecnico");

                    b.Navigation("ListEducacionBasica");

                    b.Navigation("ListEducacionSuperior");

                    b.Navigation("ListExperienciaLaboral");

                    b.Navigation("ListFormacion");

                    b.Navigation("ListOtroConocimiento");

                    b.Navigation("ListPersonaInduccion");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.Pregunta", b =>
                {
                    b.Navigation("ListRespuesta");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.ServiceGroupModel", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.TipoCertificacion", b =>
                {
                    b.Navigation("ListFormacion");
                });

            modelBuilder.Entity("IVSoftware.Web.Models.TipoEmpresa", b =>
                {
                    b.Navigation("ListExperienciaLaboral");
                });
#pragma warning restore 612, 618
        }
    }
}
